import Crop from '../Crop.js';
export default new Crop({
  id: 'aloe',
  name: 'Aloe',
  cat: 'Medicinal Herb',
  emoji: '🌵',
  planting: {
    zone6: 'Grow in containers year-round; move outdoors May–Sep, indoors before first frost. Not winter-hardy in zone 6.',
    depth: 'Plant pups or divisions at same depth as nursery; 1–2" for small offsets',
    spacing: '12–18" apart if mass planting in containers; one plant per 6–8" pot minimum',
    ph: '7.0–8.5',
    sun: 'Full sun to bright indirect light; direct outdoor sun in morning, afternoon shade in peak summer',
    zone3: 'Container only; strictly indoors except summer',
    zone4: 'Container only; outdoors Jun–Aug only',
    zone5: 'Container only; outdoors May–Sep',
    zone7: 'Container or ground with heavy winter protection; zone 7b borderline',
    zone8: 'Can overwinter in ground in sheltered sites with frost protection; containers still safest',
    zone9: 'Perennial in ground; thrives outdoors year-round',
  },
  zones: {
    '6': { timing: 'Move outdoors May; bring indoors Sep–Oct before first frost; no outdoor winter survival', plantingStart: 5, plantingEnd: 9, harvestStart: 1, harvestEnd: 12 },
  },
  special: 'Aloe vera (Aloe barbadensis miller) is a succulent perennial grown primarily as a medicinal and household plant. The clear gel inside the thick leaves soothes burns, sunburn, minor cuts, and skin irritation. In zone 6, treat as a houseplant that summers outdoors. Grows best when slightly root-bound — do not over-pot. Propagates readily from offsets ("pups") that emerge at the base. Allow soil to dry completely between waterings — overwatering is the #1 cause of death.',
  water: { in: '0.25', note: 'Drought-tolerant succulent — water deeply but infrequently. Allow soil to dry completely between waterings (every 2–3 weeks indoors in winter; every 7–10 days outdoors in summer). Never let sit in standing water. Use well-draining cactus/succulent potting mix.' },
  fertilizer: { type: 'Minimal — diluted balanced succulent fertilizer', amount: 'Half-strength balanced liquid fertilizer', freq: 'Once per month during the active growing season (Apr–Sep only); do not fertilize in fall or winter' },
  companions: {
    good: [
      { name: 'Marigolds', why: 'Good container companion outdoors in summer; both tolerate heat and some drought' },
      { name: 'Lavender', why: 'Shares Mediterranean drought-tolerant conditions; compatible sun and drainage needs' },
      { name: 'Rosemary', why: 'Same dry, sunny, well-draining soil preference; compatible outdoors in summer' },
      { name: 'Thyme', why: 'Low-growing drought-tolerant companion; compatible care requirements' },
    ],
    bad: [
      { name: 'Mint', why: 'Mint requires consistent moisture — opposite of what aloe needs; one will suffer' },
      { name: 'Basil', why: 'Basil requires frequent watering incompatible with aloe\'s dry-soil preference' },
      { name: 'Spinach', why: 'Moisture-loving vegetables are not compatible companions with succulents' },
    ],
  },
  companionDist: 'Best grown alone or with other succulents and drought-tolerant Mediterranean herbs; incompatible with moisture-loving plants',
  animals: 'Toxic to cats and dogs if ingested — the latex layer (yellow sap just under skin) contains aloin, a laxative compound. Keep out of reach of pets. Hummingbirds visit aloe flowers outdoors in warm climates.',
  diseases: [
    { name: 'Root Rot', desc: 'Most common problem — caused entirely by overwatering or poor drainage. Leaves turn yellow, soft, and mushy at base. Remove from pot; cut away rotted roots with sterile knife; allow to dry 24 hours; repot in fresh dry cactus mix. Do not water for 1 week after repotting.' },
    { name: 'Aloe Rust', desc: 'Orange-brown circular spots on leaves. Fungal disease favored by cool, humid conditions. Improve air circulation; reduce humidity; apply copper fungicide if severe.' },
    { name: 'Soft Rot (Bacterial)', desc: 'Water-soaked, slimy lesions. Caused by overwatering combined with poor air circulation. Remove and destroy affected leaves; improve drainage and airflow.' },
  ],
  pests: 'Mealybugs (most common houseplant pest — dab with rubbing alcohol on cotton swab; neem oil spray), scale insects (same treatment as mealybugs), fungus gnats (allow soil to dry more completely between waterings; yellow sticky traps), spider mites in dry indoor air (wipe leaves with damp cloth; increase humidity slightly).',
  rotation: { family: 'Asphodelaceae (Aloe genus)', cycle: 'Perennial succulent — indefinite lifespan if properly cared for. Repot every 2–3 years or when root-bound and pups are crowding the pot. Divide pups to propagate new plants.' },
  stages: [
    { label: 'Pup', title: 'Offset / pup stage', desc: 'Small offsets emerge at base of mother plant. Allow pups to reach 3–4 inches before separating. Gently detach with a clean knife, allow cut to callous 24 hours, then plant in dry cactus mix.' },
    { label: 'Juvenile', title: 'Young plant', desc: 'Grows slowly in first 6–12 months. Do not over-water during establishment. First true succulent leaves develop characteristic spotted pattern when young.' },
    { label: 'Mature', title: 'Harvest-ready plant', desc: 'Mature plants (12–18+ months) have thick, firm leaves filled with gel. Harvest outer leaves only — cut at base with a clean knife. Inner leaves continue to grow.' },
    { label: 'Outdoor summer', title: 'Summering outdoors', desc: 'Move outdoors after last frost to a bright spot with some afternoon shade. Acclimate gradually over 1–2 weeks to prevent sunburn (yes, aloe can get sunburned). Growth accelerates outdoors.' },
    { label: 'Bloom', title: 'Flowering (mature plants)', desc: 'Mature plants (3+ years) may send up a tall flower spike with tubular orange-yellow flowers indoors or when summered outdoors. Blooming does not harm the plant.' },
  ],
  nutrition: {
    calories: 0, water: 0, protein: 0, carbs: 0, fiber: 0, sugars: 0, fat: 0,
    saturated: 0, monounsat: 0, polyunsat: 0,
    vitA: 0, vitD: 0, vitE: 0, vitK: 0,
    vitC: 0, vitB1: 0, vitB2: 0, vitB3: 0, vitB5: 0, vitB6: 0,
    vitB7: 0, vitB9: 0, vitB12: 0, choline: 0,
    calcium: 0, phosphorus: 0, magnesium: 0, sodium: 0, potassium: 0, chloride: 0,
    iron: 0, zinc: 0, copper: 0, manganese: 0, selenium: 0, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Grown as a medicinal and topical plant, not for food. The clear inner gel is used topically for burns, sunburn, minor cuts, eczema, and dry skin. The yellow latex layer (aloin) just under the skin is a powerful laxative and is toxic — do not ingest the whole leaf. Aloe vera juice products sold commercially have the aloin removed.',
  },
  size: { weight: 'Mature leaves: 50–200g each', dimensions: 'Mature plants 1–3 ft tall and wide; leaves 12–24" long', notes: 'Dwarf varieties (Aloe vera \'Minibelle\') stay under 12 inches — ideal for windowsills; standard plants can become quite large over several years' },
});
