import Crop from '../Crop.js';
export default new Crop({
  id: 'apple-tree',
  name: 'Apple Tree',
  cat: 'Fruit Tree',
  emoji: '🍎',
  planting: {
    zone6: 'Plant bare-root trees in early spring (Mar–Apr) before bud break, or container-grown in fall',
    depth: 'Crown at soil level',
    spacing: '15–25 ft apart (dwarf 8–10 ft)',
    ph: '6.0–7.0',
    sun: 'Full sun (6–8 hours minimum)',
    zone3: 'Plant May after last frost; choose hardy varieties (Haralson, Zestar)',
    zone4: 'Plant late Apr–May; varieties: Honeycrisp, Cortland',
    zone5: 'Plant Apr; wide variety selection',
    zone7: 'Plant Feb–Mar; choose low-chill varieties',
    zone8: 'Plant Jan–Feb; requires low-chill varieties (Anna, Dorsett Golden)',
    zone9: 'Plant Dec–Jan; only ultra-low-chill varieties (TropicSweet)',
  },
  zones: {
    '6': { timing: 'Plant early spring (Mar–Apr); harvest Aug–Oct depending on variety', plantingStart: 3, plantingEnd: 4, harvestStart: 8, harvestEnd: 10 },
  },
  special: 'Most varieties require a cross-pollinating partner within 50 ft. Requires 500–1200 chill hours (below 45°F) depending on variety. Dwarf rootstock recommended for home gardens.',
  water: { in: '1–1.5', note: 'Deep watering once or twice a week; consistent moisture critical during fruit development (Jun–Aug). Reduce in fall.' },
  fertilizer: { type: '10-10-10 balanced (young trees); low nitrogen once bearing', amount: '1 cup per year of tree age up to 10 cups', freq: 'Once in early spring before bud break; avoid late-season feeding' },
  companions: {
    good: [
      { name: 'Marigolds', why: 'Repel codling moth and aphids when planted around the drip line' },
      { name: 'Chives', why: 'Deter apple scab and powdery mildew' },
      { name: 'Nasturtiums', why: 'Trap crop for aphids; attract beneficial insects' },
      { name: 'Comfrey', why: 'Dynamic accumulator; mulched leaves add potassium and calcium' },
    ],
    bad: [
      { name: 'Potatoes', why: 'Share blight pathogens; potato blight can infect apple foliage' },
      { name: 'Fennel', why: 'Allelopathic to most fruit trees; inhibits growth' },
    ],
  },
  companionDist: 'Keep grass away from trunk out to 2 ft; apply wood chip mulch in a 3–4 ft ring',
  animals: 'Honeybees essential for pollination. Mason bees are highly efficient pollinators.',
  diseases: [
    { name: 'Apple Scab', desc: 'Fungal disease causing olive-green spots on leaves and fruit. Spray sulfur or copper fungicide from bud break through petal fall. Choose resistant varieties (Liberty, Freedom, Enterprise).' },
    { name: 'Fire Blight', desc: 'Bacterial disease causing branches to look burned. Prune 12 inches below infection; sterilize tools between cuts with 10% bleach. Avoid high-nitrogen fertilizer.' },
    { name: 'Powdery Mildew', desc: 'White powdery coating on young shoots. Prune affected tips; improve air circulation; spray potassium bicarbonate.' },
    { name: 'Cedar-Apple Rust', desc: 'Orange gelatinous growths on nearby Eastern red cedar infect apple leaves. Remove nearby cedar galls; choose resistant varieties.' },
  ],
  pests: 'Codling moth (hang pheromone traps May–Sep; bag individual fruits), apple maggot (red sphere traps), plum curculio (kaolin clay spray), aphids (horticultural oil in early spring), Japanese beetle (hand-pick or neem oil).',
  rotation: { family: 'Rosaceae', cycle: 'Permanent planting — site carefully; do not replant in soil where another apple or stone fruit has grown within 10 years (replant disease)' },
  stages: [
    { label: 'Yr 1–2', title: 'Establishment', desc: 'Focus on root development. Prune to a central leader or open vase. Remove any fruit that sets so energy goes to roots.' },
    { label: 'Yr 3–5', title: 'Juvenile growth', desc: 'First fruiting may begin. Continue annual dormant pruning in late Feb–Mar. Establish scaffold branches.' },
    { label: 'Yr 5+', title: 'Bearing', desc: 'Full production. Annual dormant pruning keeps tree open and productive. Thin fruit to 6 inches apart in Jun for large, quality apples.' },
    { label: 'Spring', title: 'Bloom', desc: 'White to pink blossoms appear Apr–May. Critical pollination window — avoid spraying insecticides during bloom.' },
    { label: 'Summer', title: 'Fruit development', desc: 'June drop is normal. Thin remaining fruit. Water consistently. Watch for scab and codling moth.' },
    { label: 'Fall', title: 'Harvest', desc: 'Harvest when flesh is firm and starchy-sweet (starch-iodine test). Store in cool (32–40°F), humid conditions.' },
  ],
  nutrition: {
    calories: 52, water: 85.6, protein: 0.3, carbs: 13.8, fiber: 2.4, sugars: 10.4, fat: 0.2,
    saturated: 0, monounsat: 0.1, polyunsat: 0.1,
    vitA: 3, vitD: 0, vitE: 0.2, vitK: 2.2,
    vitC: 4.6, vitB1: 0.02, vitB2: 0.03, vitB3: 0.1, vitB5: 0.06, vitB6: 0.04,
    vitB7: 0, vitB9: 3, vitB12: 0, choline: 3.4,
    calcium: 6, phosphorus: 11, magnesium: 5, sodium: 1, potassium: 107, chloride: 0,
    iron: 0.1, zinc: 0.04, copper: 0.03, manganese: 0.04, selenium: 0, iodine: 0,
    chromium: 1, molybdenum: 0, fluoride: 0,
    notes: 'Per 100g raw apple with skin. Rich in quercetin and pectin (soluble fiber) which support gut health and cholesterol management.',
  },
  size: { weight: '100–300g per fruit', dimensions: '2.5–3.5" diameter', notes: 'Dwarf trees produce full-size fruit. Thin to one fruit per 6" for best size.' },
});
