import Crop from '../Crop.js';
export default new Crop({
  id: 'basil',
  name: 'Basil',
  cat: 'Herb',
  emoji: '🌿',
  planting: {
    zone6: 'Start indoors Apr (6–8 weeks before last frost); transplant May after soil warms to 60°F',
    depth: '¼" (seed); transplant at soil level',
    spacing: '12–18" apart',
    ph: '6.0–7.0',
    sun: 'Full sun (6–8 hours)',
    zone3: 'Start indoors late Mar; transplant Jun',
    zone4: 'Start indoors early Apr; transplant late May',
    zone5: 'Start indoors Apr; transplant mid-May',
    zone7: 'Direct sow or transplant late Apr',
    zone8: 'Direct sow Mar–Apr; fall crop Sep–Oct',
    zone9: 'Direct sow Feb–Mar; again Sep–Oct',
  },
  zones: {
    '6': { timing: 'Transplant May–Jun; harvest Jun–Sep; bolts in heat', plantingStart: 5, plantingEnd: 6, harvestStart: 6, harvestEnd: 9 },
  },
  special: 'Highly cold-sensitive — dies at 50°F. Pinch flower spikes immediately to prolong leaf production. Harvest in morning after dew dries for best flavor. Sweet Genovese is most popular; Thai basil has anise notes.',
  water: { in: '1', note: 'Keep evenly moist but not waterlogged. Water at base — wet leaves invite fungal disease. Wilting in afternoon heat is normal if mornings are moist.' },
  fertilizer: { type: 'Balanced organic (fish emulsion or compost tea)', amount: 'Diluted half-strength', freq: 'Every 2–3 weeks; avoid heavy nitrogen which reduces flavor concentration' },
  companions: {
    good: [
      { name: 'Tomatoes', why: 'Classic pairing — basil repels thrips, aphids, and tomato hornworm; may enhance tomato flavor' },
      { name: 'Peppers', why: 'Repels aphids and spider mites from pepper plants' },
      { name: 'Asparagus', why: 'Repels asparagus beetles' },
      { name: 'Marigolds', why: 'Combined pest-repellent effect against whiteflies and aphids' },
    ],
    bad: [
      { name: 'Sage', why: 'Allelopathic — sage inhibits basil germination and growth when planted closely' },
      { name: 'Thyme', why: 'Competing moisture preferences; thyme prefers dry, basil prefers moist' },
      { name: 'Fennel', why: 'Fennel inhibits most herbs including basil' },
    ],
  },
  companionDist: 'Plant 12–18 inches from tomatoes for best effect; close enough for aromatic interaction',
  animals: 'Pollinators love basil flowers — allow some plants to flower at season end for bees.',
  diseases: [
    { name: 'Downy Mildew', desc: 'Yellowing leaves with grey-purple fuzz underneath. Use resistant varieties (Eleonora); improve air circulation; avoid overhead watering.' },
    { name: 'Fusarium Wilt', desc: 'Sudden wilting and brown streaking in stem. No cure — remove plant immediately; do not replant basil in same spot for 3 years.' },
    { name: 'Root Rot', desc: 'Caused by overwatering or poor drainage. Ensure well-draining soil; water only when top inch is dry.' },
  ],
  pests: 'Japanese beetles (hand-pick), aphids (strong water spray or neem oil), slugs (diatomaceous earth), spider mites (increase humidity, neem oil).',
  rotation: { family: 'Lamiaceae (Mint family)', cycle: 'Annual herb; rotate annually to prevent fusarium buildup' },
  stages: [
    { label: 'Sprout', title: 'Germination', desc: 'Seeds germinate in 5–10 days at 70°F+. Keep warm and moist.' },
    { label: 'Seedling', title: 'Early growth', desc: 'First true leaves appear. Begin hardening off transplants 1–2 weeks before moving outside.' },
    { label: 'Harvest', title: 'Active harvest', desc: 'Begin harvesting when plant has 6–8 leaves. Always cut above a leaf node. Pinch out flower buds as they appear.' },
    { label: 'Bolt', title: 'Flowering', desc: 'Hot weather triggers flowering. Flavor becomes slightly bitter. Pinch flowers to extend harvest or allow to set seed for saving.' },
  ],
  nutrition: {
    calories: 23, water: 92.1, protein: 3.2, carbs: 2.7, fiber: 1.6, sugars: 0.3, fat: 0.6,
    saturated: 0, monounsat: 0.1, polyunsat: 0.4,
    vitA: 264, vitD: 0, vitE: 0.8, vitK: 414,
    vitC: 18, vitB1: 0.03, vitB2: 0.08, vitB3: 0.9, vitB5: 0.21, vitB6: 0.16,
    vitB7: 0, vitB9: 68, vitB12: 0, choline: 11.4,
    calcium: 177, phosphorus: 56, magnesium: 64, sodium: 4, potassium: 295, chloride: 0,
    iron: 3.2, zinc: 0.81, copper: 0.39, manganese: 1.15, selenium: 0.3, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Used in small culinary amounts. Exceptionally high in vitamin K (414 µg per 100g). Rich in linalool and eugenol — aromatic compounds with anti-inflammatory properties.',
  },
  size: { weight: 'N/A — harvested by leaf/stem', dimensions: 'Plants 12–24" tall at maturity', notes: 'Compact varieties like Spicy Globe stay under 12 inches; great for containers' },
});
