import Crop from '../Crop.js';
export default new Crop({
  id: 'blackberries',
  name: 'Blackberries',
  cat: 'Berry Shrub',
  emoji: '🫐',
  planting: {
    zone6: 'Plant bare-root canes Mar–Apr; container plants Apr–May',
    depth: '1–2" deeper than nursery depth; crowns just below soil surface',
    spacing: '3–5 ft apart in rows 8 ft wide',
    ph: '5.5–7.0',
    sun: 'Full sun to partial shade (6+ hours for best yield)',
    zone3: 'Plant May; choose very hardy varieties (Illini Hardy)',
    zone4: 'Plant late Apr–May; Chester, Illini Hardy',
    zone5: 'Plant Apr–early May',
    zone7: 'Plant Feb–Mar',
    zone8: 'Plant Jan–Feb; choose thornless varieties',
    zone9: 'Plant Dec–Jan; limited varieties for low-chill climates',
  },
  zones: {
    '6': { timing: 'Plant Mar–Apr; harvest Jul–Aug', plantingStart: 3, plantingEnd: 4, harvestStart: 7, harvestEnd: 8 },
  },
  special: 'Primocane-fruiting varieties (Prime-Ark Freedom) fruit on first-year canes AND second-year canes. Erect thornless varieties (Chester, Triple Crown) easiest to manage. Tip-prune new canes at 4 ft to encourage side branching.',
  water: { in: '1–1.5', note: 'Consistent moisture critical during fruit development. Drip irrigation preferred — wet foliage promotes disease. Increase to 2 in/week during ripening.' },
  fertilizer: { type: 'Balanced 10-10-10', amount: '5–6 oz per plant', freq: 'Once in early spring as buds swell; avoid late-season nitrogen which delays dormancy' },
  companions: {
    good: [
      { name: 'Marigolds', why: 'Repel nematodes and other soil pests' },
      { name: 'Mint', why: 'Deters aphids and ants that farm aphids (keep contained — mint spreads aggressively)' },
      { name: 'Tansy', why: 'Repels flying insects and ants' },
    ],
    bad: [
      { name: 'Raspberries', why: 'Can share verticillium wilt and raspberry crown borer — plant at least 100 ft apart' },
      { name: 'Roses', why: 'Same family; share diseases like cane blight and botrytis' },
      { name: 'Eggplant', why: 'Shares verticillium wilt pathogen' },
      { name: 'Tomatoes', why: 'Same verticillium wilt concern — avoid planting in rotation' },
    ],
  },
  companionDist: 'Plant companions outside the main cane rows; runners can crowd out low plants within rows',
  animals: 'Excellent habitat plant — supports native bees, butterflies, and birds. Canes provide overwintering habitat for beneficial insects.',
  diseases: [
    { name: 'Orange Rust', desc: 'Bright orange pustules on underside of leaves in spring. No cure — remove and destroy entire plant including roots immediately.' },
    { name: 'Cane Blight', desc: 'Dark lesions on canes causing dieback. Prune out infected canes well below infection; sterilize pruners.' },
    { name: 'Rosette (Double Blossom)', desc: 'Distorted, witch-broom growth. No cure; remove infected plant. Spread by eriophyid mites.' },
    { name: 'Botrytis Fruit Rot', desc: 'Grey mold on ripening fruit. Improve air circulation; harvest frequently; avoid overhead watering.' },
  ],
  pests: 'Spotted wing drosophila (fine mesh netting at ripening), raspberry crown borer (dig and destroy infested crowns), Japanese beetle (hand-pick or kaolin clay), aphids (neem oil or ladybug release).',
  rotation: { family: 'Rosaceae (Rubus)', cycle: 'Permanent planting. Remove floricanes (second-year canes) after they fruit; new primocanes replace them annually.' },
  stages: [
    { label: 'Spring', title: 'Primocane emergence', desc: 'New first-year canes (primocanes) emerge from roots. These will fruit next year on lateral branches.' },
    { label: 'Summer', title: 'Floricane fruiting', desc: 'Second-year canes (floricanes) bloom and produce fruit. Harvest when berries are fully black and come off easily.' },
    { label: 'Post-harvest', title: 'Cane removal', desc: 'Cut floricanes to the ground immediately after fruiting. Train new primocanes to trellis; tip-prune at 4 ft.' },
    { label: 'Fall', title: 'Late primocane growth', desc: 'Primocanes harden off for winter. Apply mulch around base after first frost.' },
  ],
  nutrition: {
    calories: 43, water: 88.2, protein: 1.4, carbs: 9.6, fiber: 5.3, sugars: 4.9, fat: 0.5,
    saturated: 0, monounsat: 0, polyunsat: 0.3,
    vitA: 11, vitD: 0, vitE: 1.2, vitK: 19.8,
    vitC: 21, vitB1: 0.02, vitB2: 0.03, vitB3: 0.6, vitB5: 0.28, vitB6: 0.03,
    vitB7: 0, vitB9: 25, vitB12: 0, choline: 8.5,
    calcium: 29, phosphorus: 22, magnesium: 20, sodium: 1, potassium: 162, chloride: 0,
    iron: 0.6, zinc: 0.53, copper: 0.17, manganese: 0.65, selenium: 0.4, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'High in anthocyanins and ellagic acid — potent antioxidants. Excellent fiber content supports digestive health.',
  },
  size: { weight: '3–8g per berry', dimensions: '¾–1" diameter', notes: 'Chester and Triple Crown produce large berries; flavor best when fully ripe (black and slightly soft)' },
});
