import Crop from '../Crop.js';
export default new Crop({
  id: 'blueberries',
  name: 'Blueberries',
  cat: 'Berry Shrub',
  emoji: '🫐',
  planting: {
    zone6: 'Plant bare-root or container plants Mar–Apr; two cultivars required for cross-pollination',
    depth: 'Crown at or just above soil level; do not bury',
    spacing: '4–6 ft apart (highbush); rows 10 ft apart',
    ph: '4.5–5.5 (critical — must acidify soil)',
    sun: 'Full sun (6–8 hours)',
    zone3: 'Plant May; half-high varieties (Northblue, Northsky)',
    zone4: 'Plant May; half-high or hardy highbush (Patriot, Northland)',
    zone5: 'Plant Apr–May; highbush (Bluecrop, Blueray)',
    zone7: 'Plant Feb–Mar; southern highbush varieties',
    zone8: 'Plant Jan–Feb; southern highbush (O\'Neal, Sunshine Blue)',
    zone9: 'Plant Dec–Jan; rabbiteye or southern highbush low-chill varieties',
  },
  zones: {
    '6': { timing: 'Plant Mar–Apr; harvest Jul–Aug depending on variety', plantingStart: 3, plantingEnd: 4, harvestStart: 7, harvestEnd: 8 },
  },
  special: 'SOIL pH IS CRITICAL — soil must be 4.5–5.5 or plants will not thrive. Amend with elemental sulfur months before planting; test annually. Need 2+ varieties for good yield. Highbush takes 3–4 years to reach full production.',
  water: { in: '1–2', note: 'Shallow roots require consistent moisture. Mulch heavily with pine bark or wood chips (4–6 inches) to retain moisture and maintain acidity. Do not let dry out.' },
  fertilizer: { type: 'Acid fertilizer (ammonium sulfate or azalea/rhododendron formula)', amount: '1 oz ammonium sulfate per year of plant age, up to 8 oz', freq: 'Split between early spring and mid-May; never feed after Jul or fruiting is delayed' },
  companions: {
    good: [
      { name: 'Thyme', why: 'Low-growing companion that shares acid soil preference; deters some pests' },
      { name: 'Rhododendrons', why: 'Same pH requirements; aesthetically compatible; no resource competition' },
      { name: 'Pine trees', why: 'Fallen needles help maintain acidic mulch environment' },
    ],
    bad: [
      { name: 'Tomatoes', why: 'Tomatoes prefer neutral pH (6.0–7.0) — incompatible soil requirements' },
      { name: 'Peppers', why: 'Same pH conflict; both will suffer in a compromise soil' },
      { name: 'Fennel', why: 'Allelopathic; inhibits growth of most plants including blueberries' },
    ],
  },
  companionDist: 'Isolate in dedicated acid-soil beds; modifying soil pH throughout a mixed garden is impractical',
  animals: 'Bumble bees are primary pollinators. Net bushes with bird netting when fruit begins to ripen — birds are the #1 threat to yield.',
  diseases: [
    { name: 'Mummyberry', desc: 'Most serious blueberry disease. Berries turn pink then dry into hard "mummies". Rake up and destroy mummies before bud break; apply mulch to prevent spore release.' },
    { name: 'Blueberry Stem Blight', desc: 'Rapid wilting and death of individual canes. Prune well below infection; improve drainage. Avoid wounding canes.' },
    { name: 'Botrytis Blight', desc: 'Grey mold on blossoms and berries in wet springs. Improve air circulation; remove infected tissue.' },
  ],
  pests: 'Spotted wing drosophila (use fine mesh netting), blueberry maggot (yellow sticky traps + spinosad), blueberry tip borer (prune out infested tips), birds (netting — most critical protection).',
  rotation: { family: 'Ericaceae (Heath family)', cycle: 'Permanent planting — 20–30 year lifespan. Renew old unproductive canes by pruning oldest 20% annually.' },
  stages: [
    { label: 'Yr 1–2', title: 'Establishment', desc: 'Remove flower buds years 1–2 to direct energy to root growth. Mulch heavily with pine bark.' },
    { label: 'Yr 3–4', title: 'First harvest', desc: 'Allow fruiting. Yields increase each year. Prune oldest/weakest canes in late winter.' },
    { label: 'Bloom', title: 'Flowering', desc: 'White bell-shaped flowers in Apr–May. Cross-pollination between two varieties dramatically increases yield.' },
    { label: 'Harvest', title: 'Berry ripening', desc: 'Berries turn blue 1–3 weeks before they\'re ripe. Wait for berries to drop easily — fully ripe blueberries are sweeter with more antioxidants.' },
  ],
  nutrition: {
    calories: 57, water: 84.2, protein: 0.7, carbs: 14.5, fiber: 2.4, sugars: 9.9, fat: 0.3,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 3, vitD: 0, vitE: 0.6, vitK: 19.3,
    vitC: 9.7, vitB1: 0.04, vitB2: 0.04, vitB3: 0.4, vitB5: 0.12, vitB6: 0.05,
    vitB7: 0.9, vitB9: 6, vitB12: 0, choline: 6,
    calcium: 6, phosphorus: 12, magnesium: 6, sodium: 1, potassium: 77, chloride: 0,
    iron: 0.3, zinc: 0.16, copper: 0.06, manganese: 0.34, selenium: 0.1, iodine: 0,
    chromium: 0.2, molybdenum: 0, fluoride: 0,
    notes: 'Highest antioxidant content of commonly consumed fruits. Rich in anthocyanins (responsible for blue color) linked to brain health, heart health, and reduced inflammation.',
  },
  size: { weight: '1–4g per berry', dimensions: '½–¾" diameter', notes: 'Jersey and Elliot varieties produce the largest highbush berries' },
});
