import Crop from '../Crop.js';
export default new Crop({
  id: 'cabbage',
  name: 'Cabbage',
  cat: 'Brassica',
  emoji: '🥬',
  planting: {
    zone6: 'Spring: start indoors Feb–Mar; transplant Apr–early May. Fall: direct sow Jul or transplant Aug for Oct harvest.',
    depth: '¼–½" (seed)',
    spacing: '12–18" apart in rows 24" wide',
    ph: '6.0–7.5',
    sun: 'Full sun (6+ hours)',
    zone3: 'Start indoors Mar; transplant Jun; fall crop not practical',
    zone4: 'Start indoors Feb–Mar; transplant May; fall crop Jul',
    zone5: 'Start indoors Feb; transplant Apr–May; fall crop Jul–early Aug',
    zone7: 'Spring transplant Mar–Apr; fall direct sow Aug–Sep',
    zone8: 'Fall–winter primary season; transplant Sep–Nov',
    zone9: 'Grow as fall/winter/spring crop; transplant Oct–Jan',
  },
  zones: {
    '6': { timing: 'Spring transplant Apr–May; Fall direct sow Jul–Aug; harvest Jun or Oct', plantingStart: 4, plantingEnd: 5, harvestStart: 6, harvestEnd: 10 },
  },
  special: 'Cool-season crop — flavor improves after light frost. Bolts and splits in heat. For fall crops, count back 70–80 days from first expected frost. Use row covers to extend season and deter cabbage moth.',
  water: { in: '1–1.5', note: 'Consistent moisture is critical — uneven watering causes heads to split. Avoid wetting foliage. Reduce watering slightly as heads approach maturity.' },
  fertilizer: { type: 'High nitrogen initially; reduce as head forms', amount: '¼ cup 10-10-10 per transplant', freq: 'Side-dress with nitrogen fertilizer 3 weeks after transplant; stop when head begins to form' },
  companions: {
    good: [
      { name: 'Dill', why: 'Attracts wasps that parasitize imported cabbageworm' },
      { name: 'Marigolds', why: 'Deter cabbage moths and aphids' },
      { name: 'Onions', why: 'Strong scent masks cabbage from pests; reduce aphid pressure' },
      { name: 'Mint', why: 'Repels cabbage moth and aphids (keep contained)' },
      { name: 'Nasturtiums', why: 'Trap crop for aphids; attract aphid predators' },
    ],
    bad: [
      { name: 'Strawberries', why: 'Brassicas inhibit strawberry growth' },
      { name: 'Tomatoes', why: 'Allelopathic interaction — tomatoes inhibit brassica growth' },
      { name: 'Fennel', why: 'Inhibits most brassicas; keep well separated' },
      { name: 'Grapes', why: 'Brassicas allegedly inhibit grape vine growth' },
    ],
  },
  companionDist: 'Use tall companion plants on north side to avoid shading; space 18 inches minimum from most companions',
  animals: 'Parasitic wasps (Trichogramma sp.) are key predators of cabbageworm eggs. Attract with dill and yarrow.',
  diseases: [
    { name: 'Clubroot', desc: 'Roots swell and distort; plant wilts and yellows. Raise soil pH to 7.0+ with lime. Destroy infected plants; do not compost. Avoid replanting brassicas in same bed for 7+ years.' },
    { name: 'Black Rot', desc: 'V-shaped yellow lesions from leaf margins; black veins. Bacterial disease spread by rain splash. Use disease-free seed; avoid overhead watering; rotate crops.' },
    { name: 'Downy Mildew', desc: 'Yellow patches on leaves with grey-white fuzz underneath. Improve air circulation; avoid wet foliage. Spray copper fungicide preventively.' },
  ],
  pests: 'Imported cabbageworm (Bacillus thuringiensis — Bt), cabbage looper (Bt spray), aphids (insecticidal soap or strong water spray), flea beetles (row covers at transplant), root maggot (collar around stem base).',
  rotation: { family: 'Brassicaceae (Mustard family)', cycle: 'Rotate every 3–4 years; do not follow another brassica (broccoli, kale, turnips) in same bed' },
  stages: [
    { label: 'Seedling', title: 'Transplant establishment', desc: 'Harden off transplants 7–10 days before moving outside. Plant on overcast day or in evening.' },
    { label: 'Rosette', title: 'Leaf expansion', desc: 'Outer leaves grow and expand. Fertilize with nitrogen. Install row cover now to prevent moth egg-laying.' },
    { label: 'Head', title: 'Head formation', desc: 'Outer leaves cup inward and head begins to form. Reduce nitrogen; maintain water consistency.' },
    { label: 'Harvest', title: 'Mature head', desc: 'Harvest when head feels firm when squeezed. Cut at base; leave outer leaves. After harvest, leave root in ground — often produces small side shoots.' },
  ],
  nutrition: {
    calories: 25, water: 92.2, protein: 1.3, carbs: 5.8, fiber: 2.5, sugars: 3.2, fat: 0.1,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 5, vitD: 0, vitE: 0.2, vitK: 76,
    vitC: 36.6, vitB1: 0.06, vitB2: 0.04, vitB3: 0.2, vitB5: 0.21, vitB6: 0.12,
    vitB7: 0, vitB9: 43, vitB12: 0, choline: 10.7,
    calcium: 40, phosphorus: 26, magnesium: 12, sodium: 18, potassium: 170, chloride: 0,
    iron: 0.5, zinc: 0.18, copper: 0.02, manganese: 0.16, selenium: 0.3, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Excellent source of vitamin C and vitamin K. Contains glucosinolates (sulforaphane precursors) linked to cancer prevention. Red/purple cabbage contains significantly more antioxidants than green.',
  },
  size: { weight: '0.5–3 kg per head', dimensions: '6–10" diameter', notes: 'Savoy types have crinkled leaves and milder flavor; red types take longer to mature' },
});
