import Crop from '../Crop.js';
export default new Crop({
  id: 'cantaloupe',
  name: 'Cantaloupe',
  cat: 'Fruiting Vine',
  emoji: '🍈',
  planting: {
    zone6: 'Start indoors early May (2–3 weeks before last frost); transplant late May after soil reaches 70°F',
    depth: '½–1" (seed), 2–3 seeds per hill then thin to 2',
    spacing: '18–24" in rows, hills 4–6 ft apart; or hills 6 ft apart',
    ph: '6.0–6.5',
    sun: 'Full sun (8+ hours)',
    zone3: 'Short season — start indoors early May; transplant Jun; choose early varieties (Minnesota Midget)',
    zone4: 'Start indoors early May; transplant late May; use row covers to extend season',
    zone5: 'Start indoors Apr; transplant mid-May',
    zone7: 'Direct sow late Apr; transplant Apr',
    zone8: 'Direct sow late Mar–Apr',
    zone9: 'Direct sow Mar or Aug for fall crop',
  },
  zones: {
    '6': { timing: 'Transplant late May; harvest Aug–Sep (75–90 days from transplant)', plantingStart: 5, plantingEnd: 6, harvestStart: 8, harvestEnd: 9 },
  },
  special: 'Requires warm soil and air temperatures — do not rush transplanting. Reduce watering as fruits approach maturity for sweeter flavor. Slip-test for ripeness: ripe cantaloupe separates from vine with gentle pressure ("full slip"). Bush varieties (Bushstar, Minnesota Midget) ideal for small gardens.',
  water: { in: '1–2', note: 'Deep, infrequent watering. Critical during vine establishment and fruit development. Stop or greatly reduce watering 1–2 weeks before harvest to concentrate sugars.' },
  fertilizer: { type: 'Balanced, then high potassium at fruiting', amount: '½ cup 10-10-10 per hill at planting', freq: 'Side-dress when vines begin to run; switch to low-nitrogen/high-potassium at flowering to promote fruit quality' },
  companions: {
    good: [
      { name: 'Corn', why: 'Corn provides windbreak; cantaloupe vines shade out weeds around corn base' },
      { name: 'Marigolds', why: 'Repel aphids, cucumber beetles, and nematodes' },
      { name: 'Nasturtiums', why: 'Trap crop for aphids and cucumber beetles' },
      { name: 'Radishes', why: 'Deter cucumber beetles when planted nearby' },
    ],
    bad: [
      { name: 'Potatoes', why: 'Both susceptible to blight; competing vines create disease pressure' },
      { name: 'Cucumbers', why: 'Can cross-pollinate affecting seed quality; compete for space and nutrients' },
    ],
  },
  companionDist: 'Vines spread 6–8 ft; give ample space or train onto a trellis with slings to support heavy fruit',
  animals: 'Bees essential for pollination. Male flowers appear first — don\'t be alarmed if early flowers don\'t set fruit.',
  diseases: [
    { name: 'Powdery Mildew', desc: 'White powder on older leaves. Most common cantaloupe disease. Improve air circulation; spray potassium bicarbonate or sulfur; choose resistant varieties.' },
    { name: 'Downy Mildew', desc: 'Yellow angular spots on upper leaf surface with grey-purple sporulation below. Apply copper fungicide preventively in wet weather.' },
    { name: 'Bacterial Wilt', desc: 'Sudden wilting of vines. Caused by cucumber beetles. No cure — prevent cucumber beetles with row covers early season (remove at flowering for pollination).' },
    { name: 'Alternaria Blight', desc: 'Dark lesions on older leaves. Rotate crops; avoid overhead watering.' },
  ],
  pests: 'Cucumber beetles (kaolin clay, row covers early, trap crops), squash vine borer (unlikely on cantaloupe vs squash), aphids (neem oil), spider mites (water spray, neem oil in hot dry weather).',
  rotation: { family: 'Cucurbitaceae (Gourd family)', cycle: 'Rotate every 2–3 years; do not follow cucumbers, squash, or pumpkins in same bed' },
  stages: [
    { label: 'Sprout', title: 'Germination / transplant', desc: 'Germinates in 5–10 days at 75°F+. Handle roots carefully when transplanting — do not disturb.' },
    { label: 'Vine', title: 'Vine running', desc: 'Vines spread rapidly in warm weather. Train or direct away from paths. Keep weeds cleared.' },
    { label: 'Bloom', title: 'Flowering', desc: 'Male flowers appear first. Female flowers (with tiny fruit at base) appear 1–2 weeks later. Bees must move pollen between flowers.' },
    { label: 'Set', title: 'Fruit development', desc: 'Fruits swell rapidly over 4–6 weeks. Slip each fruit onto small board or tile to prevent rot. Reduce water.' },
    { label: 'Harvest', title: 'Full slip', desc: 'Ripe when skin turns tan-beige, netting is prominent, and fruit slips from vine with light pressure. Fragrant when ripe.' },
  ],
  nutrition: {
    calories: 34, water: 90.2, protein: 0.8, carbs: 8.2, fiber: 0.9, sugars: 7.9, fat: 0.2,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 169, vitD: 0, vitE: 0.1, vitK: 2.5,
    vitC: 36.7, vitB1: 0.04, vitB2: 0.02, vitB3: 0.7, vitB5: 0.11, vitB6: 0.07,
    vitB7: 0, vitB9: 21, vitB12: 0, choline: 7.6,
    calcium: 9, phosphorus: 15, magnesium: 12, sodium: 16, potassium: 267, chloride: 0,
    iron: 0.2, zinc: 0.18, copper: 0.04, manganese: 0.04, selenium: 0.4, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Excellent source of beta-carotene (vitamin A) and vitamin C. High water content makes it very hydrating.',
  },
  size: { weight: '0.5–2 kg per fruit', dimensions: '5–7" diameter (typical netted muskmelon)', notes: 'Small-fruited varieties like Minnesota Midget produce 4-inch fruits perfect for small gardens' },
});
