import Crop from '../Crop.js';
export default new Crop({
  id: 'carrots',
  name: 'Carrots',
  cat: 'Root Vegetable',
  emoji: '🥕',
  planting: {
    zone6: 'Direct sow Mar–May for summer; Jul–Aug for fall/winter harvest. Thin to 2–3" apart.',
    depth: '¼" (very shallow — needs light to germinate)',
    spacing: '2–3" apart after thinning; rows 12" wide',
    ph: '6.0–6.8',
    sun: 'Full sun to light partial shade',
    zone3: 'Direct sow mid-May to Jun; fall crop not practical',
    zone4: 'Direct sow May; fall sow mid-Jul',
    zone5: 'Direct sow Apr; fall sow Jul–early Aug',
    zone7: 'Direct sow Mar–Apr; fall sow Aug–Sep',
    zone8: 'Direct sow Feb–Mar; fall sow Sep–Oct; overwinter in ground',
    zone9: 'Grow as fall–spring crop; sow Oct–Jan',
  },
  zones: {
    '6': { timing: 'Sow Mar–May; fall sow Jul–Aug; harvest 70–80 days from sowing', plantingStart: 3, plantingEnd: 5, harvestStart: 6, harvestEnd: 11 },
  },
  special: 'Loose, deep, rock-free soil is essential — compaction causes forked roots. Mix sand into clay soils. Cover seeds with vermiculite or burlap to retain moisture during slow (2–3 week) germination. Fall-grown carrots taste sweeter after frost converts starches to sugars.',
  water: { in: '1', note: 'Consistent, even moisture. Uneven watering causes cracking. After thinning, mulch to retain moisture. Reduce watering slightly as roots approach maturity.' },
  fertilizer: { type: 'Low nitrogen, high phosphorus (bone meal, 0-10-10)', amount: '2 lbs bone meal per 25 sq ft worked into soil before sowing', freq: 'Single application at bed preparation; excess nitrogen causes forked roots and excessive tops' },
  companions: {
    good: [
      { name: 'Onions', why: 'Onion scent repels carrot fly; carrot scent deters onion fly — classic mutualistic pairing' },
      { name: 'Leeks', why: 'Same mutual pest deterrence as onions' },
      { name: 'Rosemary', why: 'Strong scent confuses carrot fly' },
      { name: 'Lettuce', why: 'Shallow roots don\'t compete; provides living mulch; fills gaps between carrot rows' },
      { name: 'Tomatoes', why: 'Tomatoes emit solanine which repels carrot fly' },
    ],
    bad: [
      { name: 'Dill', why: 'Cross-pollinates with carrots if both are flowering; also inhibits germination when mature' },
      { name: 'Fennel', why: 'Strongly allelopathic — inhibits carrot growth' },
      { name: 'Parsnips', why: 'Same pest pressures compete for identical resources' },
    ],
  },
  companionDist: 'Interplant onions every 4 inches within carrot rows for maximum carrot fly deterrence',
  animals: 'Beneficial nematodes control carrot weevil larvae in soil. Ground beetles eat carrot fly pupae.',
  diseases: [
    { name: 'Carrot Leaf Blight', desc: 'Brown spots and blighted foliage in wet conditions. Use resistant varieties; avoid overhead watering; crop rotation.' },
    { name: 'Root Rot (Cavity Spot)', desc: 'Elliptical cavities on roots. Caused by Pythium in poorly drained soil. Improve drainage; avoid waterlogged conditions.' },
    { name: 'Aster Yellows', desc: 'Hairy secondary roots; yellowing foliage. Spread by leafhoppers. Use row covers; control leafhopper populations.' },
  ],
  pests: 'Carrot fly/rust fly (avoid bruising foliage which releases attractant scent; use fleece row cover; grow beside onions), wireworms (beneficial nematodes in soil), carrot weevil (crop rotation).',
  rotation: { family: 'Apiaceae (Carrot family)', cycle: 'Rotate every 3 years; do not follow parsnips, celery, or parsley in same bed' },
  stages: [
    { label: 'Germinate', title: 'Slow germination', desc: 'Takes 14–21 days at 55–75°F. Keep soil consistently moist — critical period. Cover with burlap if soil dries quickly.' },
    { label: 'Thin', title: 'Thinning', desc: 'Thin to 2–3 inches when seedlings are 2 inches tall. Thinning is critical — crowded carrots stay small and forked.' },
    { label: 'Growth', title: 'Root development', desc: 'Tops grow vigorously. Root is developing underground — maintain consistent moisture.' },
    { label: 'Harvest', title: 'Mature roots', desc: 'Harvest when shoulder is ½–¾ inch diameter at soil surface. Loosen soil with fork before pulling. Fall carrots sweeten after several frosts.' },
  ],
  nutrition: {
    calories: 41, water: 88.3, protein: 0.9, carbs: 9.6, fiber: 2.8, sugars: 4.7, fat: 0.2,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 835, vitD: 0, vitE: 0.7, vitK: 13.2,
    vitC: 5.9, vitB1: 0.07, vitB2: 0.06, vitB3: 1.0, vitB5: 0.27, vitB6: 0.14,
    vitB7: 0, vitB9: 19, vitB12: 0, choline: 8.8,
    calcium: 33, phosphorus: 35, magnesium: 12, sodium: 69, potassium: 320, chloride: 0,
    iron: 0.3, zinc: 0.24, copper: 0.05, manganese: 0.14, selenium: 0.1, iodine: 0,
    chromium: 1.5, molybdenum: 0, fluoride: 0,
    notes: 'One of the richest plant sources of beta-carotene (pro-vitamin A). Cooked carrots have higher bioavailable carotenoids than raw. Excellent source of falcarinol, a cancer-protective compound.',
  },
  size: { weight: '50–150g per carrot', dimensions: '6–8" long, ½–¾" diameter', notes: 'Chantenay types do well in heavy clay soil; Imperator types need deep loose soil; Nantes are best for flavor' },
});
