import Crop from '../Crop.js';
export default new Crop({
  id: 'cherry-tree',
  name: 'Cherry Tree',
  cat: 'Fruit Tree',
  emoji: '🍒',
  planting: {
    zone6: 'Plant bare-root trees in early spring (Mar–Apr) before buds break; container plants through May',
    depth: 'Crown at soil level',
    spacing: 'Sweet cherry: 25–35 ft apart; tart/sour: 18–20 ft (dwarf 8–10 ft)',
    ph: '6.0–7.0',
    sun: 'Full sun (6–8 hours)',
    zone3: 'Sour/tart varieties only (Meteor, North Star); plant May',
    zone4: 'Hardy tart varieties; plant late Apr–May',
    zone5: 'Sweet and tart; plant Apr–May',
    zone7: 'Plant Feb–Mar; sweet cherries excellent here',
    zone8: 'Plant Jan–Feb; Minnie Royal and Royal Lee for low-chill sweet cherries',
    zone9: 'Very limited; only ultra-low-chill varieties',
  },
  zones: {
    '6': { timing: 'Plant early spring; bloom Apr; harvest Jun–Jul for sweet, Jul–Aug for sour', plantingStart: 3, plantingEnd: 4, harvestStart: 6, harvestEnd: 8 },
  },
  special: 'Sweet cherries require cross-pollination (plant 2 compatible varieties). Sour/tart cherries (Montmorency) are self-fruitful. Net trees when fruit colors — birds will strip a tree in hours. Late frosts during bloom can destroy the entire crop.',
  water: { in: '1', note: 'Deep watering once a week; increase during fruit development. Avoid waterlogging — cherry is highly susceptible to root rot in wet soils.' },
  fertilizer: { type: 'Balanced 10-10-10; low nitrogen once bearing', amount: '1 lb per year of tree age up to 8 lbs', freq: 'Once in early spring before bloom; avoid late-season feeding' },
  companions: {
    good: [
      { name: 'Marigolds', why: 'Deter aphids and other pests at the tree base' },
      { name: 'Garlic', why: 'Planted around base deters borers and some fungal diseases' },
      { name: 'Comfrey', why: 'Dynamic nutrient accumulator; provides potassium and calcium when used as mulch' },
    ],
    bad: [
      { name: 'Potatoes', why: 'Share verticillium wilt; potatoes in orchard soil can infect tree roots' },
      { name: 'Wheat', why: 'Hosts Xiphinema nematodes which spread cherry leaf roll virus' },
    ],
  },
  companionDist: 'Keep grass-free ring of 2–3 ft around trunk; mulch with wood chips',
  animals: 'Bees essential for sweet cherry pollination. Net immediately when fruits color to exclude birds.',
  diseases: [
    { name: 'Brown Rot', desc: 'Most serious cherry disease. Brown, mummified fruit with grey spore masses. Remove all mummies; prune for air circulation; spray sulfur or copper at petal fall.' },
    { name: 'Black Knot', desc: 'Black galls on branches. Prune 4 inches below gall; bag and destroy. Can girdle and kill branches.' },
    { name: 'Cherry Leaf Spot', desc: 'Purple-red spots on leaves; premature defoliation. Apply copper fungicide at petal fall; rake and destroy fallen leaves.' },
    { name: 'Bacterial Canker', desc: 'Gummy ooze from bark lesions. Avoid pruning in wet weather; copper spray in fall.' },
  ],
  pests: 'Birds (netting — most critical), cherry fruit fly (yellow sticky traps + spinosad), peach tree borer (apply Bt or beneficial nematodes to soil around trunk in Jun), aphids (horticultural oil at bud swell).',
  rotation: { family: 'Rosaceae (Prunus genus)', cycle: 'Permanent planting — 20–30+ year lifespan. Do not replant in old cherry or stone fruit site.' },
  stages: [
    { label: 'Dormant', title: 'Winter dormancy', desc: 'Prune during dormancy (late Feb before bud swell). Remove crossing branches and water sprouts.' },
    { label: 'Bloom', title: 'Spring bloom', desc: 'Early Apr in zone 6. Highly frost-sensitive — protect with frost cloth if frost threatens during bloom.' },
    { label: 'Fruit set', title: 'Cell division', desc: 'Fruitlets rapidly expand. June drop is normal. Water consistently.' },
    { label: 'Harvest', title: 'Cherry harvest', desc: 'Sweet cherries: harvest when fully colored and sweet (not sour). Sour/tart: harvest when fully red and slightly soft for pies; firmer for fresh eating.' },
  ],
  nutrition: {
    calories: 50, water: 82.3, protein: 1.0, carbs: 12.2, fiber: 1.6, sugars: 8.5, fat: 0.3,
    saturated: 0.1, monounsat: 0.1, polyunsat: 0.1,
    vitA: 3, vitD: 0, vitE: 0.1, vitK: 2.1,
    vitC: 7, vitB1: 0.03, vitB2: 0.03, vitB3: 0.2, vitB5: 0.2, vitB6: 0.05,
    vitB7: 0, vitB9: 4, vitB12: 0, choline: 6.1,
    calcium: 13, phosphorus: 21, magnesium: 11, sodium: 0, potassium: 222, chloride: 0,
    iron: 0.4, zinc: 0.07, copper: 0.06, manganese: 0.07, selenium: 0, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Sour cherries contain significantly more antioxidants than sweet. Rich in melatonin and anthocyanins. Tart cherry juice studied for muscle recovery and sleep improvement.',
  },
  size: { weight: '8–15g per cherry', dimensions: '¾–1" diameter', notes: 'Bing and Rainier are popular sweet varieties; Montmorency is the classic sour/pie cherry' },
});
