import Crop from '../Crop.js';
export default new Crop({
  id: 'corn',
  name: 'Corn',
  cat: 'Grain / Vegetable',
  emoji: '🌽',
  planting: {
    zone6: 'Direct sow mid-May to Jun when soil reaches 60°F; succession plant every 2 weeks through Jun',
    depth: '1–1.5"',
    spacing: '9–12" in rows 30–36" apart; plant in blocks of 4+ rows for pollination',
    ph: '5.8–6.8',
    sun: 'Full sun (8+ hours)',
    zone3: 'Sow late May–early Jun; short-season varieties only (Earlivee, Sugar Buns)',
    zone4: 'Sow late May; choose 65–75 day varieties',
    zone5: 'Sow mid-May; wide selection',
    zone7: 'Sow late Apr',
    zone8: 'Sow Mar–Apr; also possible Aug for fall crop',
    zone9: 'Sow Mar; second crop Aug–Sep',
  },
  zones: {
    '6': { timing: 'Sow mid-May; harvest Aug–Sep (75–90 days from sowing)', plantingStart: 5, plantingEnd: 6, harvestStart: 8, harvestEnd: 9 },
  },
  special: 'Wind-pollinated — must plant in blocks (not single rows) of at least 4x4 for good pollination. Sweet corn needs isolation from field corn, popcorn, and other sweet corn types to prevent cross-pollination affecting sweetness. Harvest within 20 minutes of cooking for peak sweetness.',
  water: { in: '1–1.5', note: 'Critical periods: at tassel/silk emergence and during ear development. Drought stress at silking causes poor kernel fill (gaps in ear).' },
  fertilizer: { type: 'High nitrogen', amount: '¼ cup 10-10-10 per 5 ft row at planting', freq: 'Side-dress with nitrogen when plants are knee-high (12–18 inches) and again at tasseling' },
  companions: {
    good: [
      { name: 'Beans', why: 'Three Sisters — beans fix nitrogen for corn; corn provides bean pole support' },
      { name: 'Squash', why: 'Three Sisters — squash leaves shade soil preventing weeds and moisture loss' },
      { name: 'Cucumbers', why: 'Use corn stalks as support; shading at base deters cucumber beetle' },
      { name: 'Marigolds', why: 'Deter corn earworm moths and aphids' },
    ],
    bad: [
      { name: 'Tomatoes', why: 'Both susceptible to same fungal diseases; compete for water and nutrients' },
      { name: 'Fennel', why: 'Inhibits germination and growth of most vegetables including corn' },
      { name: 'Celery', why: 'Allelopathic to corn in close proximity' },
    ],
  },
  companionDist: 'Three Sisters spacing: plant corn first, add beans 1 week later (1 ft from corn), squash 2 weeks after corn (3 ft out)',
  animals: 'Beneficial insects control corn earworm. Bats consume adult moths. Trichogramma wasps parasitize earworm eggs.',
  diseases: [
    { name: 'Gray Leaf Spot', desc: 'Rectangular grey-tan lesions on leaves. Most serious in humid conditions. Choose resistant varieties; rotate crops; no-till reduces infection.' },
    { name: 'Northern Corn Leaf Blight', desc: 'Large tan cigar-shaped lesions. Avoid overhead watering; resistant varieties (use the NCLB designation on seed packet).' },
    { name: 'Common Smut', desc: 'Grotesque grey-white galls on ears and tassels. Remove and destroy galls before they burst. Do not compost. Rotate crops.' },
    { name: 'Stewart\'s Wilt', desc: 'Bacterial disease spread by corn flea beetle. Water-soaked streaks on leaves. Control flea beetles with row covers early season.' },
  ],
  pests: 'Corn earworm (apply Bt or mineral oil in silk; pheromone traps), corn borer (Bt spray on tassels), aphids (syrphid flies and ladybugs; avoid broad-spectrum pesticides), raccoons (electric fence or wire mesh), deer (8-ft fence).',
  rotation: { family: 'Poaceae (Grass family)', cycle: 'Rotate every 2–3 years; do not follow sorghum or other grasses; excellent after legumes (beans, peas)' },
  stages: [
    { label: 'Emerge', title: 'Germination', desc: 'Germinates in 7–10 days when soil is 60°F+. Cold, wet soil causes seed rot.' },
    { label: 'V-stage', title: 'Vegetative growth', desc: 'Rapid growth in warm weather. Side-dress nitrogen at knee-high stage.' },
    { label: 'Tassel', title: 'Tasseling', desc: 'Male pollen-shedding tassels emerge at top. Silk emerges from ear tips within 2–3 days. Each silk strand connects to a kernel — all must be pollinated.' },
    { label: 'Milk', title: 'Milk stage', desc: 'Kernels are plump and milky when pierced. Peak eating quality. Harvest now.' },
    { label: 'Dough', title: 'Dough / Dent', desc: 'Kernels begin to dent and dry. Too late for fresh eating; dry for corn meal or popcorn varieties.' },
  ],
  nutrition: {
    calories: 86, water: 76.0, protein: 3.3, carbs: 19.0, fiber: 2.7, sugars: 3.2, fat: 1.4,
    saturated: 0.2, monounsat: 0.4, polyunsat: 0.6,
    vitA: 9, vitD: 0, vitE: 0.1, vitK: 0.3,
    vitC: 6.8, vitB1: 0.2, vitB2: 0.07, vitB3: 1.7, vitB5: 0.72, vitB6: 0.09,
    vitB7: 6, vitB9: 42, vitB12: 0, choline: 29,
    calcium: 2, phosphorus: 89, magnesium: 37, sodium: 15, potassium: 270, chloride: 0,
    iron: 0.5, zinc: 0.46, copper: 0.05, manganese: 0.16, selenium: 0.6, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Values for fresh sweet corn. Contains lutein and zeaxanthin which support eye health. Niacin in corn is bound and only released by nixtamalization (soaking in lime water).',
  },
  size: { weight: '200–350g per ear with husk', dimensions: '7–9" ears with 16–18 rows of kernels', notes: 'Bicolor and supersweet varieties stay sweeter longer after harvest' },
});
