import Crop from '../Crop.js';
export default new Crop({
  id: 'cucumbers',
  name: 'Cucumbers',
  cat: 'Fruiting Vine',
  emoji: '🥒',
  planting: {
    zone6: 'Direct sow mid-May to Jun; start indoors early May for 2-week head start',
    depth: '½–1"',
    spacing: '12" apart on trellis; 18–24" for bush types; rows 4–5 ft apart',
    ph: '6.0–7.0',
    sun: 'Full sun (6–8 hours)',
    zone3: 'Start indoors early May; transplant Jun; choose short-season varieties',
    zone4: 'Start indoors late Apr; transplant late May',
    zone5: 'Direct sow mid-May; start indoors Apr',
    zone7: 'Direct sow late Apr',
    zone8: 'Direct sow late Mar–Apr; second crop Aug',
    zone9: 'Direct sow Mar; second crop Aug–Sep',
  },
  zones: {
    '6': { timing: 'Sow mid-May; harvest Jul–Sep (55–65 days from sowing)', plantingStart: 5, plantingEnd: 6, harvestStart: 7, harvestEnd: 9 },
  },
  special: 'Train vertically on trellis for better air circulation and easier harvest. Harvest frequently (every 1–2 days when producing) — overripe cucumbers turn yellow, become bitter, and stop new fruit production. Burpless varieties have thinner skin and fewer seeds.',
  water: { in: '1–1.5', note: 'Consistent moisture is critical — uneven watering causes bitter cucumbers. Increase to 2 in/week in peak heat. Water at base; wet foliage promotes powdery mildew.' },
  fertilizer: { type: 'Balanced then high potassium', amount: '1 tbsp 10-10-10 per transplant', freq: 'At planting; side-dress with balanced fertilizer when first flowers appear; switch to low-nitrogen high-potassium when fruiting' },
  companions: {
    good: [
      { name: 'Beans', why: 'Beans fix nitrogen; cucumbers benefit from consistent nitrogen availability' },
      { name: 'Corn', why: 'Corn provides windbreak and light shade; cucumber vines cover corn base to suppress weeds' },
      { name: 'Dill', why: 'Attracts predatory wasps and ladybugs that control aphids and cucumber beetles' },
      { name: 'Marigolds', why: 'Repel cucumber beetles and nematodes' },
      { name: 'Nasturtiums', why: 'Trap crop for aphids; attract beneficials' },
      { name: 'Sunflowers', why: 'Attract pollinators critical for cucumber fruit set' },
    ],
    bad: [
      { name: 'Sage', why: 'Inhibits cucumber growth when planted nearby' },
      { name: 'Potatoes', why: 'Attract blight; compete for resources' },
      { name: 'Melons', why: 'Compete for space; can cross-pollinate affecting seed quality' },
    ],
  },
  companionDist: 'Plant marigolds every 12–18 inches along cucumber row perimeter',
  animals: 'Bees essential for pollination. Parthenocarpic (self-fruiting) varieties produce without bees — ideal for greenhouse growing.',
  diseases: [
    { name: 'Powdery Mildew', desc: 'White coating on leaves, usually older ones first. Most common cucumber problem. Improve air circulation (trellis); spray potassium bicarbonate; choose resistant varieties.' },
    { name: 'Downy Mildew', desc: 'Yellow angular spots on upper leaf surface. Spreads rapidly in humid conditions. Copper fungicide; avoid overhead watering.' },
    { name: 'Bacterial Wilt', desc: 'Sudden wilting — no recovery. Spread by cucumber beetles. Prevent beetles with row covers at planting (remove at flowering). Test by cutting stem and touching cut ends — presence of sticky thread = bacterial wilt.' },
    { name: 'Angular Leaf Spot', desc: 'Water-soaked angular spots that turn grey-white. Avoid overhead irrigation; copper spray; crop rotation.' },
  ],
  pests: 'Cucumber beetles (row covers early season; kaolin clay; pyrethrin spray), aphids (neem oil; blast with water), spider mites (increase humidity; neem), squash bugs (hand-remove eggs; diatomaceous earth).',
  rotation: { family: 'Cucurbitaceae (Gourd family)', cycle: 'Rotate every 2–3 years; do not follow squash, melons, or pumpkins in same bed' },
  stages: [
    { label: 'Sprout', title: 'Germination', desc: 'Emerges in 7–10 days at 70°F+. Cold, wet soil causes seed rot.' },
    { label: 'Vine', title: 'Vine development', desc: 'Vines grow rapidly. Train onto trellis. Remove row covers when flowers appear for pollinator access.' },
    { label: 'Bloom', title: 'Flowering', desc: 'Male flowers appear first. Female flowers (with tiny cucumber at base) appear 1–2 weeks later.' },
    { label: 'Harvest', title: 'Continuous harvest', desc: 'Harvest slicing cucumbers at 6–8 inches; pickling types at 2–4 inches. Check every 1–2 days. Never let cucumbers turn yellow on vine.' },
  ],
  nutrition: {
    calories: 15, water: 95.2, protein: 0.7, carbs: 3.6, fiber: 0.5, sugars: 1.7, fat: 0.1,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 5, vitD: 0, vitE: 0.0, vitK: 16.4,
    vitC: 2.8, vitB1: 0.03, vitB2: 0.03, vitB3: 0.1, vitB5: 0.26, vitB6: 0.04,
    vitB7: 0, vitB9: 7, vitB12: 0, choline: 6,
    calcium: 16, phosphorus: 24, magnesium: 13, sodium: 2, potassium: 147, chloride: 0,
    iron: 0.3, zinc: 0.2, copper: 0.04, manganese: 0.08, selenium: 0.3, iodine: 0,
    chromium: 0.9, molybdenum: 0, fluoride: 0,
    notes: 'Extremely high water content (95%) makes cucumbers very hydrating. Peel contains the majority of the nutrients — eat unpeeled when possible.',
  },
  size: { weight: '150–300g per cucumber (slicing)', dimensions: '6–9" long, 1.5–2" diameter', notes: 'Pickling varieties: 2–4" long; Persian cucumbers: thin-skinned and seedless, 5–7"' },
});
