import Crop from '../Crop.js';
export default new Crop({
  id: 'dogwood',
  name: 'Dogwood',
  cat: 'Ornamental Tree',
  emoji: '🌸',
  planting: {
    zone6: 'Plant balled-and-burlapped or container trees Apr–May or fall (Sep–Oct)',
    depth: 'Crown at or slightly above soil level; never bury deeply',
    spacing: '20–25 ft from other large trees and structures',
    ph: '5.5–6.5',
    sun: 'Part shade to full sun; partial shade reduces leaf scorch and extends bloom',
    zone3: 'Not reliably hardy; not recommended',
    zone4: 'Marginal; use Cornus sericea (red-twig dogwood, a shrub) instead of C. florida',
    zone5: 'Cornus florida possible in sheltered sites; Cornus kousa more reliable',
    zone6: 'Both Cornus florida and Cornus kousa (kousa dogwood) thrive',
    zone7: 'Both species excellent; multi-season interest',
    zone8: 'Cornus kousa preferred; Florida dogwood stressed in heat; select disease-resistant varieties',
    zone9: 'Neither species well-suited; consider Cornus alternifolia',
  },
  zones: {
    '6': { timing: 'Plant Apr–May or fall; blooms Apr–May; red berries Sep–Oct; fall foliage Oct', plantingStart: 4, plantingEnd: 5, harvestStart: 9, harvestEnd: 10 },
  },
  special: 'Flowering dogwood (Cornus florida) is a native woodland understory tree — iconic spring bloomer. Kousa dogwood (C. kousa) blooms 2–3 weeks later, has edible berry-like fruit, and is more disease-resistant. Plant where it gets morning sun and afternoon shade for best performance.',
  water: { in: '1–1.5', note: 'Deep watering during establishment. Drought-stressed dogwoods are highly susceptible to borers and anthracnose. Mulch deeply (3–4 inches) to retain moisture but keep mulch away from trunk.' },
  fertilizer: { type: 'Balanced slow-release or low-nitrogen', amount: 'Light application — 1 lb 10-10-10 per inch trunk diameter', freq: 'Once in early spring; avoid over-fertilizing which promotes lush but disease-susceptible growth' },
  companions: {
    good: [
      { name: 'Hostas', why: 'Thrive in the dappled shade beneath dogwood canopy' },
      { name: 'Ferns', why: 'Woodland native companions; share moisture and shade preferences' },
      { name: 'Azaleas', why: 'Similar acid-soil requirement; bloom at same time for layered spring display' },
      { name: 'Wild Ginger', why: 'Native groundcover that thrives in dogwood understory conditions' },
    ],
    bad: [
      { name: 'Grass', why: 'Lawn grass and dogwood roots compete; mowers and trimmers frequently injure trunk — the primary entry point for borer' },
      { name: 'Black Walnut', why: 'Juglone toxicity harms dogwood; keep at least 50 ft away' },
    ],
  },
  companionDist: 'Mulch ring 4 ft radius around trunk; plant shade companions at drip line and beyond',
  animals: 'Critical wildlife tree — red berries consumed by 36+ bird species including migratory thrushes and waxwings. Excellent for pollinators during spring bloom.',
  diseases: [
    { name: 'Dogwood Anthracnose', desc: 'Most serious dogwood disease; common in C. florida. Brown blotches on leaves with purple border; dieback. Plant C. kousa or disease-resistant hybrids (Aurora, Celestial). Avoid overhead watering; remove dead wood.' },
    { name: 'Powdery Mildew', desc: 'White coating on leaves. Increasingly common. Improve air circulation; fungicide if severe. C. kousa much less susceptible.' },
    { name: 'Spot Anthracnose', desc: 'Small tan spots with purple halos on flower bracts. Usually cosmetic only. Copper fungicide at bud break in wet springs.' },
  ],
  pests: 'Dogwood borer (most serious pest; keep trunk healthy and wound-free; prevent grass/mower damage), scales (horticultural oil spray while dormant), club gall midge (prune and destroy galled branch tips in spring).',
  rotation: { family: 'Cornaceae', cycle: 'Permanent ornamental tree — 25–50 year lifespan. Choose site carefully.' },
  stages: [
    { label: 'Spring', title: 'Bloom', desc: 'White or pink bracts (not true petals) appear Apr–May. True flowers are the small yellow cluster in the center of each bract group. Peak ornamental season.' },
    { label: 'Summer', title: 'Foliage and growth', desc: 'Dark green leaves provide layered canopy. Slow to moderate growth rate (1–2 ft/year when established).' },
    { label: 'Fall', title: 'Berries and color', desc: 'Bright red berry clusters ripen Sep–Oct — excellent wildlife food. Foliage turns scarlet-purple. Multi-season ornamental peak.' },
    { label: 'Winter', title: 'Branch structure', desc: 'Horizontal branching pattern creates outstanding winter silhouette. Flower buds visible at branch tips.' },
  ],
  nutrition: {
    calories: 0, water: 0, protein: 0, carbs: 0, fiber: 0, sugars: 0, fat: 0,
    saturated: 0, monounsat: 0, polyunsat: 0,
    vitA: 0, vitD: 0, vitE: 0, vitK: 0,
    vitC: 0, vitB1: 0, vitB2: 0, vitB3: 0, vitB5: 0, vitB6: 0,
    vitB7: 0, vitB9: 0, vitB12: 0, choline: 0,
    calcium: 0, phosphorus: 0, magnesium: 0, sodium: 0, potassium: 0, chloride: 0,
    iron: 0, zinc: 0, copper: 0, manganese: 0, selenium: 0, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Ornamental tree — not grown for food. Berries are technically edible but astringent and not palatable. Grown for flowers, fall color, and wildlife value.',
  },
  size: { weight: 'N/A', dimensions: '15–30 ft tall, 15–25 ft spread at maturity', notes: 'Cornus kousa tends slightly smaller; both have horizontal tiered branching at maturity' },
});
