import Crop from '../Crop.js';
export default new Crop({
  id: 'elderberries',
  name: 'Elderberries',
  cat: 'Berry Shrub',
  emoji: '🫐',
  planting: {
    zone6: 'Plant bare-root canes or container plants Mar–Apr or fall; two varieties for best pollination',
    depth: 'Same as nursery depth or 2–3" deeper for cuttings',
    spacing: '6–10 ft between plants; 10–12 ft between rows',
    ph: '5.5–6.5',
    sun: 'Full sun to partial shade (6+ hours preferred)',
    zone3: 'Hardy to -40°F; plant May; excellent choice for cold climates',
    zone4: 'Plant Apr–May; very hardy shrub',
    zone5: 'Plant Apr; vigorous grower in this zone',
    zone7: 'Plant Feb–Mar',
    zone8: 'Plant Dec–Feb; can suffer in prolonged summer heat without moisture',
    zone9: 'Marginally adapted; needs supplemental irrigation',
  },
  zones: {
    '6': { timing: 'Plant Mar–Apr; harvest Aug–Sep for berries; flowers Jun–Jul', plantingStart: 3, plantingEnd: 4, harvestStart: 8, harvestEnd: 9 },
  },
  special: 'Raw elderberries and all green parts of the plant contain cyanogenic glycosides — always cook berries before consuming. Sambucus nigra (American/European elderberry) is the species used for elderberry syrup, wine, and medicine. Plant 2 varieties for cross-pollination (Adams, Nova, Bob Gordon).',
  water: { in: '1–1.5', note: 'Moderate and consistent. Tolerates brief waterlogging but not prolonged. Drought reduces berry production significantly.' },
  fertilizer: { type: 'Balanced organic or compost', amount: '2–3 inches of compost worked into soil each spring', freq: 'Top-dress with compost each spring; light 10-10-10 if growth is poor; avoid over-feeding which produces lush growth but poor fruiting' },
  companions: {
    good: [
      { name: 'Yarrow', why: 'Attracts beneficial insects including parasitic wasps; shares wet-meadow habitat preference' },
      { name: 'Comfrey', why: 'Dynamic accumulator; mulched leaves add nutrients; both tolerate similar moist conditions' },
      { name: 'Nasturtiums', why: 'Ground-level companion; attracts beneficial insects' },
    ],
    bad: [
      { name: 'Walnut', why: 'Juglone from walnut roots is toxic to elderberry' },
    ],
  },
  companionDist: 'Large vigorous shrub — give 10 ft clearance from structures; plant in a row for windbreak and wildlife hedge',
  animals: 'Exceptional wildlife value — berries consumed by 50+ bird species. Flowers attract hundreds of pollinator species. Important native plant in eastern North America.',
  diseases: [
    { name: 'Elderberry Leaf Spot', desc: 'Brown spots on leaves. Usually cosmetic only. Remove affected leaves; avoid overhead watering.' },
    { name: 'Powdery Mildew', desc: 'White coating on leaves in dry summers. Improve air circulation with pruning. Usually does not affect yield.' },
    { name: 'Verticillium Wilt', desc: 'Sudden wilting of canes; brown vascular tissue. Remove and destroy affected canes. Avoid planting near tomatoes, potatoes, or strawberries.' },
  ],
  pests: 'Relatively pest-resistant. Aphids (lady beetles usually control naturally), elder shoot aphid (prune and destroy infested tip growth in spring), birds (net if yield is to be retained for harvest — though birds indicate good habitat).',
  rotation: { family: 'Adoxaceae (Sambucus genus)', cycle: 'Permanent multi-year shrub (10–15+ year productive life). Renewal prune oldest canes to ground every 3–4 years.' },
  stages: [
    { label: 'Spring', title: 'New growth', desc: 'Vigorous new canes emerge from roots and established wood. Can grow 6–8 ft in a single season.' },
    { label: 'Jun–Jul', title: 'Flowering', desc: 'Large flat-topped clusters (corymbs) of tiny white flowers. Harvest some for elderflower cordial; leave the rest for fruit.' },
    { label: 'Aug–Sep', title: 'Berry harvest', desc: 'Harvest entire clusters when berries are deep purple-black and birds start eating them. Process immediately — do NOT eat raw.' },
    { label: 'Winter', title: 'Dormant pruning', desc: 'Prune out dead, damaged, or crossing canes. Remove canes 3+ years old (grey, thicker bark) to maintain vigorous new growth.' },
  ],
  nutrition: {
    calories: 73, water: 79.8, protein: 0.7, carbs: 18.4, fiber: 7.0, sugars: 0, fat: 0.5,
    saturated: 0, monounsat: 0, polyunsat: 0,
    vitA: 30, vitD: 0, vitE: 0, vitK: 0,
    vitC: 36, vitB1: 0.07, vitB2: 0.06, vitB3: 0.5, vitB5: 0.14, vitB6: 0.23,
    vitB7: 0, vitB9: 6, vitB12: 0, choline: 0,
    calcium: 38, phosphorus: 39, magnesium: 5, sodium: 6, potassium: 280, chloride: 0,
    iron: 1.6, zinc: 0.11, copper: 0.07, manganese: 0.26, selenium: 0.6, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'MUST BE COOKED — raw berries contain cyanogenic glycosides. Rich in anthocyanins, quercetin, and vitamin C. Elderberry syrup widely used for immune support. High fiber content.',
  },
  size: { weight: '3–5g per cluster', dimensions: 'Clusters 5–10" wide; individual berries 5–8mm', notes: 'Adams and Bob Gordon are top-yielding varieties for zone 5–7' },
});
