import Crop from '../Crop.js';
export default new Crop({
  id: 'garlic',
  name: 'Garlic',
  cat: 'Allium',
  emoji: '🧄',
  planting: {
    zone6: 'Plant individual cloves Oct–Nov (4–6 weeks before hard freeze); harvest following Jun–Jul',
    depth: '2" deep, pointy end up',
    spacing: '6" apart in rows 12" wide',
    ph: '6.0–7.0',
    sun: 'Full sun (6–8 hours)',
    zone3: 'Plant Sep–early Oct; mulch heavily; hardneck varieties (Rocambole, Porcelain)',
    zone4: 'Plant early Oct; hardneck varieties',
    zone5: 'Plant Oct; hardneck and softneck varieties both work',
    zone7: 'Plant late Oct–Nov',
    zone8: 'Plant Nov–Dec; softneck varieties (Silverskin, Artichoke)',
    zone9: 'Plant Nov–Jan; softneck varieties; limited hardneck success',
  },
  zones: {
    '6': { timing: 'Plant Oct–Nov; harvest Jun–Jul when lower ⅓ of leaves brown', plantingStart: 10, plantingEnd: 11, harvestStart: 6, harvestEnd: 7 },
  },
  special: 'Plant the largest cloves from the largest bulbs — clove size directly determines bulb size at harvest. Hardneck types (Rocambole, Purple Stripe) produce scapes in spring — cut scapes when they curl for a bonus harvest and to redirect energy to the bulb. Softneck types (Artichoke, Silverskin) store up to a year. Cure harvested bulbs 3–4 weeks in a dry, airy location before storing.',
  water: { in: '1', note: 'Water regularly through spring growth. Stop watering completely 2–3 weeks before harvest. Wet soil at harvest causes bulb rot in storage.' },
  fertilizer: { type: 'High nitrogen in fall, balanced in spring', amount: 'Blood meal or fish meal at 2 lbs per 25 sq ft at fall planting', freq: 'Apply high-nitrogen at planting; side-dress balanced fertilizer when tops are 6 inches tall in spring; stop all feeding after scapes appear' },
  companions: {
    good: [
      { name: 'Roses', why: 'Garlic repels aphids and the fungal diseases (blackspot) that commonly afflict roses' },
      { name: 'Tomatoes', why: 'Repels spider mites, aphids, and early blight on tomatoes' },
      { name: 'Fruit Trees', why: 'Planted around base repels borers, aphids, and rodents from gnawing bark' },
      { name: 'Carrots', why: 'Mutual pest deterrence — carrot fly and onion fly confused by each other\'s scents' },
      { name: 'Lettuce', why: 'Garlic deters aphids that commonly attack lettuce' },
    ],
    bad: [
      { name: 'Beans', why: 'Garlic and all alliums inhibit bean growth — keep strictly separate' },
      { name: 'Peas', why: 'Same allium-legume inhibition applies to all pea varieties' },
      { name: 'Asparagus', why: 'Competes for nutrients and inhibits asparagus root development' },
    ],
  },
  companionDist: 'Plant garlic 6–8 inches from most companions; keep strictly away from all legume beds',
  animals: 'Deer, rabbit, and vole repellent. Moles reportedly avoid areas with garlic.',
  diseases: [
    { name: 'White Rot', desc: 'White fluffy fungal growth at bulb base; yellowing and collapse. Most serious garlic disease. Sclerotia survive 20+ years in soil. Remove all infected plants; long rotation; avoid moving soil from infected beds.' },
    { name: 'Fusarium Basal Rot', desc: 'Pink-white mycelium at base; roots rot. Remove infected plants; ensure good drainage; crop rotation every 3–4 years.' },
    { name: 'Rust', desc: 'Bright orange pustules on leaves in spring. Usually cosmetic but reduces bulb size. Apply sulfur fungicide at first sign.' },
    { name: 'Botrytis Neck Rot', desc: 'Blue-grey mold at neck; common in wet seasons. Harvest promptly; cure thoroughly; store in dry conditions.' },
  ],
  pests: 'Onion thrips (spinosad or neem oil; use reflective mulch), bulb mites (ensure well-draining soil; avoid infected planting material), nematodes (long rotation; soil solarization).',
  rotation: { family: 'Amaryllidaceae (Allium genus)', cycle: 'Rotate every 3–4 years; do not follow onions, leeks, or shallots in the same bed' },
  stages: [
    { label: 'Fall', title: 'Root establishment', desc: 'Cloves root quickly after planting but tops may or may not emerge before winter. Roots grow through mild winters.' },
    { label: 'Spring', title: 'Rapid foliar growth', desc: 'Vigorous top growth in Mar–Apr. Mulch to control weeds. Fertilize when 6 inches tall.' },
    { label: 'Scape', title: 'Scape emergence (hardneck)', desc: 'Curling scape emerges in May–Jun. Harvest when fully curled — cut and use in stir-fries, pesto, pickles. Boosts bulb size 15–25%.' },
    { label: 'Harvest', title: 'Bulb harvest', desc: 'Harvest when lower 1/3 of leaves turn brown. Dig carefully with fork; do not pull tops. Cure in dry airy spot 3–4 weeks before storing.' },
  ],
  nutrition: {
    calories: 149, water: 58.6, protein: 6.4, carbs: 33.1, fiber: 2.1, sugars: 1.0, fat: 0.5,
    saturated: 0.1, monounsat: 0, polyunsat: 0.2,
    vitA: 0, vitD: 0, vitE: 0.1, vitK: 1.7,
    vitC: 31.2, vitB1: 0.2, vitB2: 0.11, vitB3: 0.7, vitB5: 0.6, vitB6: 1.24,
    vitB7: 0, vitB9: 3, vitB12: 0, choline: 23.2,
    calcium: 181, phosphorus: 153, magnesium: 25, sodium: 17, potassium: 401, chloride: 0,
    iron: 1.7, zinc: 1.16, copper: 0.3, manganese: 1.67, selenium: 14.2, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Exceptionally high selenium (14.2 µg per 100g) and manganese. Allicin (formed when garlic is crushed) is a potent antimicrobial and cardiovascular protective compound. Let crushed garlic rest 10 minutes before cooking to maximize allicin formation.',
  },
  size: { weight: '30–80g per bulb', dimensions: '1.5–3" diameter bulb', notes: 'Elephant garlic (Allium ampeloprasum) produces very large mild bulbs; true garlic is punchier in flavor' },
});
