import Crop from '../Crop.js';
export default new Crop({
  id: 'grapes',
  name: 'Grapes',
  cat: 'Fruiting Vine',
  emoji: '🍇',
  planting: {
    zone6: 'Plant bare-root vines Mar–Apr before buds swell; container plants Apr–May',
    depth: 'Same as nursery or 2–3" deeper; graft union above soil if grafted',
    spacing: '6–8 ft apart on trellis; rows 8–10 ft apart',
    ph: '5.5–7.0',
    sun: 'Full sun (8+ hours — essential for fruit quality and disease resistance)',
    zone3: 'Hardy varieties only (Frontenac, Marquette, Valiant)',
    zone4: 'Hardy varieties (Concord, Niagara, Frontenac)',
    zone5: 'Wide selection (Concord, Catawba, Reliance)',
    zone7: 'Excellent for American and European–American hybrids',
    zone8: 'Muscadine grapes (Carlos, Nesbitt) are the primary choice',
    zone9: 'Muscadine grapes; table grapes with heat tolerance',
  },
  zones: {
    '6': { timing: 'Plant Mar–Apr; harvest late Aug–Oct depending on variety (3–4 years to first real harvest)', plantingStart: 3, plantingEnd: 4, harvestStart: 8, harvestEnd: 10 },
  },
  special: 'Requires a sturdy trellis (7-ft posts, 2–3 horizontal wires). Most productive on a Kniffen system or VSP (Vertical Shoot Positioned) trellis. Annual dormant pruning is CRITICAL — grapevines must be aggressively pruned each winter (remove 80–90% of previous season growth) or yields collapse. Concord is the most reliable American grape for zones 5–6.',
  water: { in: '1', note: 'Deep watering; drought tolerant once established. Reduce in late summer to encourage flavor concentration. Wet conditions promote disease — drip irrigation strongly preferred.' },
  fertilizer: { type: 'Balanced; low nitrogen once established', amount: '¼ lb 10-10-10 per vine in years 1–2; ½ lb year 3+', freq: 'Once in early spring as buds swell; light potassium in Jun to support fruit; avoid late-season feeding' },
  companions: {
    good: [
      { name: 'Basil', why: 'Repels spider mites and aphids; may improve grape flavor according to some growers' },
      { name: 'Hyssop', why: 'Attracts beneficial insects and reportedly improves grape health' },
      { name: 'Clover', why: 'Living mulch under vines fixes nitrogen and attracts pollinators' },
      { name: 'Geraniums', why: 'Repel Japanese beetles which commonly damage grape leaves' },
    ],
    bad: [
      { name: 'Cabbage', why: 'Brassica family allegedly inhibits grape vine growth' },
      { name: 'Radishes', why: 'Some evidence of allelopathic effect on vines' },
    ],
  },
  companionDist: 'Plant companions at least 2 ft from vine base; keep the immediate root zone clear for irrigation',
  animals: 'Bees pollinate grape flowers (small, fragrant). Birds eat ripe grapes — netting required for table varieties. Japanese beetles are a primary pest threat.',
  diseases: [
    { name: 'Black Rot', desc: 'Most serious grape disease in the Midwest/East. Brown circular spots on leaves; black mummified berries. Remove mummies; spray copper or sulfur from bud break through mid-summer. Choose resistant varieties (Concord has good resistance).' },
    { name: 'Downy Mildew', desc: 'White cottony growth on leaf undersides; infected shoots distort. Copper fungicide at 2-week intervals in wet springs.' },
    { name: 'Powdery Mildew', desc: 'White coating on leaves and fruit. Sulfur spray; good air circulation from trellis training.' },
    { name: 'Botrytis Bunch Rot', desc: 'Grey mold on fruit at harvest. Thin clusters; improve air circulation; harvest promptly when ripe.' },
  ],
  pests: 'Japanese beetles (hand-pick; kaolin clay; neem), grape berry moth (pheromone traps; spinosad spray), grape leafhopper (encourage parasitic wasps; avoid broad-spectrum pesticides), birds (netting is most effective — essential for table grapes).',
  rotation: { family: 'Vitaceae', cycle: 'Permanent planting — 30–50+ year productive life. Choose site very carefully; avoid frost pockets and areas with poor air circulation.' },
  stages: [
    { label: 'Yr 1', title: 'Establishment', desc: 'Establish the trunk. Let vine grow freely; do not train to trellis yet. Remove all flower clusters.' },
    { label: 'Yr 2', title: 'Trunk training', desc: 'Train main trunk to trellis. Begin establishing the permanent cordon (arms). Remove all flower clusters still.' },
    { label: 'Yr 3', title: 'First harvest', desc: 'Allow a few clusters to ripen. Prune dormant vines aggressively in late Feb–Mar.' },
    { label: 'Yr 4+', title: 'Full production', desc: 'Full crops. Annual dormant pruning (remove 80-90% of canes) keeps vine productive. Spurs or canes depending on training system.' },
    { label: 'Harvest', title: 'Fruit harvest', desc: 'Grapes do not ripen further after harvest — taste test before picking. Sugar (Brix) should be 18–25 for eating; 22-25+ for wine.' },
  ],
  nutrition: {
    calories: 69, water: 80.5, protein: 0.7, carbs: 18.1, fiber: 0.9, sugars: 15.5, fat: 0.2,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 3, vitD: 0, vitE: 0.2, vitK: 14.6,
    vitC: 3.2, vitB1: 0.07, vitB2: 0.07, vitB3: 0.2, vitB5: 0.05, vitB6: 0.09,
    vitB7: 1.3, vitB9: 2, vitB12: 0, choline: 5.6,
    calcium: 10, phosphorus: 20, magnesium: 7, sodium: 2, potassium: 191, chloride: 0,
    iron: 0.4, zinc: 0.07, copper: 0.13, manganese: 0.07, selenium: 0.1, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Rich in resveratrol (especially in skin of dark/red varieties), quercetin, and anthocyanins. Grapes contain tartaric acid and malic acid unique to the fruit.',
  },
  size: { weight: '2–8g per berry', dimensions: '½–¾" diameter (table grapes)', notes: 'Concord produces medium blue-black berries with characteristic foxy flavor; Reliance produces seedless red table grapes' },
});
