import Crop from '../Crop.js';
export default new Crop({
  id: 'green-beans',
  name: 'Green Beans',
  cat: 'Legume',
  emoji: '🫘',
  planting: {
    zone6: 'Direct sow mid-May to Jun when soil reaches 60°F; succession sow every 2 weeks through Jul 1 for continuous harvest',
    depth: '1–1.5"',
    spacing: 'Bush beans: 4–6" apart; pole beans: 6–8" apart at trellis; rows 18–24" wide',
    ph: '6.0–6.8',
    sun: 'Full sun (6–8 hours)',
    zone3: 'Direct sow late May–early Jun; bush varieties for short season',
    zone4: 'Direct sow late May; bush beans most reliable',
    zone5: 'Direct sow mid-May',
    zone7: 'Direct sow late Apr–May; second crop Aug',
    zone8: 'Direct sow Mar–Apr; second crop Aug–Sep',
    zone9: 'Direct sow Mar; fall crop Aug–Sep',
  },
  zones: {
    '6': { timing: 'Sow mid-May through Jul 1; harvest Jul–Sep (50–65 days from sowing)', plantingStart: 5, plantingEnd: 7, harvestStart: 7, harvestEnd: 9 },
  },
  special: 'Do NOT transplant — beans have fragile roots. Inoculate seed with rhizobium bacteria powder for best nitrogen fixation (especially in new beds). Bush beans produce all at once (good for preserving); pole beans produce over a longer season. Harvest every 2–3 days when pods are small — overripe pods reduce production and become tough.',
  water: { in: '1', note: 'Consistent moisture — drought stress causes bean drop and tough pods. Critical during flowering and pod development. Avoid overhead watering to prevent fungal disease.' },
  fertilizer: { type: 'Low nitrogen (beans fix their own)', amount: 'Minimal — excess nitrogen produces lush foliage with few pods', freq: 'Light 5-10-10 phosphorus and potassium at planting; no nitrogen side-dressing needed if inoculated' },
  companions: {
    good: [
      { name: 'Corn', why: 'Three Sisters — beans fix nitrogen for corn; climb corn stalks as natural trellis' },
      { name: 'Squash', why: 'Three Sisters — squash shade the soil around beans and corn' },
      { name: 'Carrots', why: 'Loose carrot roots don\'t compete with bean roots; beans shade late-season carrot bolt' },
      { name: 'Cucumbers', why: 'Beans fix nitrogen; cucumbers benefit from consistent soil nitrogen' },
      { name: 'Marigolds', why: 'Deter Mexican bean beetles and nematodes' },
      { name: 'Radishes', why: 'Quick radishes fill space between bean rows without competing' },
    ],
    bad: [
      { name: 'Garlic', why: 'All alliums severely inhibit bean growth — do not plant near any allium' },
      { name: 'Onions', why: 'Same allium-legume incompatibility' },
      { name: 'Fennel', why: 'Allelopathic to most plants including beans' },
      { name: 'Beets', why: 'Compete aggressively; some evidence of mutual inhibition' },
    ],
  },
  companionDist: 'Keep beans at least 2 ft from any allium (garlic, onion, leek, chive)',
  animals: 'Bees pollinate bean flowers. Parasitic wasps control bean aphids and Mexican bean beetles.',
  diseases: [
    { name: 'Bean Mosaic Virus', desc: 'Mottled yellow-green leaves; distorted pods. Spread by aphids. No cure — remove plants; control aphids; plant resistant varieties.' },
    { name: 'Bacterial Brown Spot', desc: 'Water-soaked spots turning brown with yellow halos on pods and leaves. Use certified disease-free seed; avoid overhead watering.' },
    { name: 'Bean Rust', desc: 'Reddish-brown pustules on leaves. Apply sulfur fungicide; improve air circulation; crop rotation.' },
    { name: 'White Mold', desc: 'Cottony white growth at stem base in cool, wet conditions. Improve air circulation; avoid dense planting.' },
  ],
  pests: 'Mexican bean beetle (hand-remove egg masses; neem oil; spinosad), bean leaf beetle (row covers early season), aphids (strong water spray; lady beetles), Japanese beetles (hand-pick or kaolin clay), spider mites in heat (increase humidity; insecticidal soap).',
  rotation: { family: 'Fabaceae (Legume family)', cycle: 'Rotate every 2–3 years; excellent predecessor for corn and heavy nitrogen feeders — leaves nitrogen-enriched soil' },
  stages: [
    { label: 'Emerge', title: 'Germination', desc: 'Emerges in 7–14 days at 65°F+. Cold, wet soil causes seed rot.' },
    { label: 'Vegetative', title: 'Early growth', desc: 'Rapid growth in warm weather. Thin to proper spacing. Bush beans stay compact; pole beans need trellis.' },
    { label: 'Bloom', title: 'Flowering', desc: 'White, pink, or purple flowers appear 5–7 weeks from planting. Self-pollinating — no insect required but bees increase set.' },
    { label: 'Harvest', title: 'Pod harvest', desc: 'Harvest when pods are firm, crisp, and snap cleanly. Size of pencil thickness for best flavor. Check every 2 days.' },
  ],
  nutrition: {
    calories: 31, water: 90.3, protein: 1.8, carbs: 7.1, fiber: 2.7, sugars: 3.3, fat: 0.1,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 35, vitD: 0, vitE: 0.4, vitK: 43,
    vitC: 12.2, vitB1: 0.08, vitB2: 0.1, vitB3: 0.7, vitB5: 0.23, vitB6: 0.07,
    vitB7: 0, vitB9: 33, vitB12: 0, choline: 15.3,
    calcium: 37, phosphorus: 38, magnesium: 25, sodium: 6, potassium: 211, chloride: 0,
    iron: 1.0, zinc: 0.24, copper: 0.07, manganese: 0.22, selenium: 0.6, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Good source of vitamin K and folate. Contain chlorophyll and carotenoids. Provide prebiotic fiber that supports gut microbiome.',
  },
  size: { weight: '10–20g per pod', dimensions: '4–6" long pods', notes: 'Haricot verts (filet beans) are harvested at 3–4 inches for premium thin pods' },
});
