import Crop from '../Crop.js';
export default new Crop({
  id: 'kale',
  name: 'Kale',
  cat: 'Brassica',
  emoji: '🥬',
  planting: {
    zone6: 'Spring: direct sow Mar–Apr or transplant Apr–May. Fall: direct sow Jul–Aug for best crop — flavor peaks after frost.',
    depth: '¼–½"',
    spacing: '12–18" apart in rows 18–24" wide',
    ph: '6.0–7.5',
    sun: 'Full sun to partial shade (tolerates more shade than most vegetables)',
    zone3: 'Direct sow Jun; harvest into early fall; mulch for extended season',
    zone4: 'Direct sow mid-May; fall sow mid-Jul',
    zone5: 'Direct sow Apr–May; fall sow late Jul',
    zone7: 'Direct sow Feb–Mar; fall sow Sep; kale overwinters easily',
    zone8: 'Fall–winter primary season; plant Oct–Nov',
    zone9: 'Fall/winter/spring crop; plant Oct–Feb',
  },
  zones: {
    '6': { timing: 'Spring sow Mar–Apr; fall sow Jul–Aug; harvest Oct–Feb from fall plantings', plantingStart: 3, plantingEnd: 8, harvestStart: 5, harvestEnd: 2 },
  },
  special: 'Frost dramatically improves kale flavor — converts starches to sugars, making leaves sweeter and more tender. Lacinato (Dinosaur) kale is most cold-hardy and sweet. Curly kale is the most commonly grown. Red Russian kale is most tender and mild. Harvest outer leaves to keep plants producing for months.',
  water: { in: '1–1.5', note: 'Consistent moisture; tolerates brief drought better than most brassicas. Reduce watering slightly in fall — slight stress before frost improves flavor even more.' },
  fertilizer: { type: 'High nitrogen', amount: '¼ cup 10-10-10 per transplant or ½ lb per 10-ft row', freq: 'Side-dress nitrogen every 4–6 weeks for long-season harvests; kale is a heavy feeder' },
  companions: {
    good: [
      { name: 'Dill', why: 'Attracts parasitic wasps that control cabbageworm; plant away from kale seed saving (cross-family, no cross issues but dill bolts quickly)' },
      { name: 'Marigolds', why: 'Deter aphids and cabbage moths' },
      { name: 'Nasturtiums', why: 'Trap crop for aphids' },
      { name: 'Onions', why: 'Scent deters cabbage moth egg-laying' },
      { name: 'Garlic', why: 'Repels aphids and cabbage moth' },
    ],
    bad: [
      { name: 'Strawberries', why: 'Brassica compounds inhibit strawberry root development' },
      { name: 'Tomatoes', why: 'Allelopathic interaction; tomatoes inhibit brassica growth' },
      { name: 'Fennel', why: 'Inhibits nearly all plants including kale' },
    ],
  },
  companionDist: 'Plant garlic and onions at 12-inch intervals within kale rows for embedded pest deterrence',
  animals: 'Parasitic wasps (Trichogramma) are key for cabbageworm control — attract with dill, yarrow, and fennel planted at garden periphery.',
  diseases: [
    { name: 'Downy Mildew', desc: 'Yellow patches on upper leaf surface; grey-purple sporulation below. Apply copper fungicide preventively in wet seasons; improve air circulation.' },
    { name: 'Black Rot', desc: 'V-shaped yellow lesions from leaf margins; blackened veins. Crop rotation; disease-free seed; avoid overhead watering.' },
    { name: 'Alternaria Leaf Spot', desc: 'Concentric dark rings on older leaves. Remove affected foliage; copper spray.' },
  ],
  pests: 'Cabbageworm (Bt spray; row covers), cabbage looper (Bt spray), aphids (insecticidal soap; strong water spray; introduce ladybugs), flea beetles (row covers; diatomaceous earth), harlequin bugs in warm zones (hand-remove; neem).',
  rotation: { family: 'Brassicaceae (Mustard family)', cycle: 'Rotate every 3–4 years; do not follow cabbage, broccoli, turnips, or radishes' },
  stages: [
    { label: 'Seedling', title: 'Emergence', desc: 'Germinates quickly (4–7 days at 55–75°F). Thin to proper spacing. Install row cover against flea beetles.' },
    { label: 'Juvenile', title: 'Leaf development', desc: 'Outer leaves reach harvest size at about 60 days. Begin harvesting lower leaves.' },
    { label: 'Harvest', title: 'Continuous leaf harvest', desc: 'Pick lower/outer leaves regularly. Keep central growing point intact. Plant can produce for 3–6 months.' },
    { label: 'Frost', title: 'Flavor peak', desc: 'First hard frost (28°F) triggers maximum sugar conversion. Fall kale is dramatically sweeter than summer kale.' },
    { label: 'Overwintering', title: 'Cold resilience', desc: 'Kale survives temperatures to 10–15°F with mulching. Lacinato is hardiest. Resume growth and harvest in early spring.' },
  ],
  nutrition: {
    calories: 35, water: 89.6, protein: 2.9, carbs: 4.4, fiber: 4.1, sugars: 0.8, fat: 1.5,
    saturated: 0.2, monounsat: 0.1, polyunsat: 0.7,
    vitA: 500, vitD: 0, vitE: 1.5, vitK: 817,
    vitC: 93.4, vitB1: 0.11, vitB2: 0.13, vitB3: 1.0, vitB5: 0.09, vitB6: 0.27,
    vitB7: 0, vitB9: 141, vitB12: 0, choline: 0.5,
    calcium: 254, phosphorus: 92, magnesium: 34, sodium: 38, potassium: 447, chloride: 0,
    iron: 1.5, zinc: 0.39, copper: 0.29, manganese: 0.77, selenium: 0.9, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'One of the most nutrient-dense foods known. Extremely high vitamin K (817 µg per 100g), vitamin C, and vitamin A. Rich in lutein and zeaxanthin for eye health. Contains glucosinolates — cancer-protective compounds.',
  },
  size: { weight: 'N/A — harvested leaf by leaf', dimensions: 'Mature leaves 12–18" long', notes: 'Baby kale harvested at 4–6 weeks for salads; mature leaves better for cooking' },
});
