import Crop from '../Crop.js';
export default new Crop({
  id: 'lettuce',
  name: 'Lettuce',
  cat: 'Leafy Green',
  emoji: '🥗',
  planting: {
    zone6: 'Direct sow Mar–May (spring); succession sow every 2 weeks. Fall: sow Aug–Sep for Oct–Nov harvest.',
    depth: '⅛" (needs light to germinate — barely cover)',
    spacing: 'Leaf types: 6–8"; head types: 10–12"; rows 12" wide',
    ph: '6.0–7.0',
    sun: 'Full sun in spring; partial shade in summer to prevent bolting',
    zone3: 'Direct sow late May; short spring/fall window',
    zone4: 'Direct sow May; fall sow late Jul',
    zone5: 'Direct sow Apr; fall sow Aug',
    zone7: 'Direct sow Mar; fall sow Sep–Oct',
    zone8: 'Fall–spring crop; sow Sep–Feb',
    zone9: 'Fall–spring crop; sow Oct–Mar',
  },
  zones: {
    '6': { timing: 'Spring sow Mar–May; fall sow Aug–Sep; harvest 45–60 days from sowing', plantingStart: 3, plantingEnd: 5, harvestStart: 4, harvestEnd: 11 },
  },
  special: 'Bolts (goes to seed) quickly in heat above 75°F — flavor turns bitter. Use bolt-resistant varieties (Jericho, Sierra) for summer. Shade cloth (30–50%) dramatically extends season in summer. Ideal cut-and-come-again crop: harvest outer leaves repeatedly. Loose-leaf types are easiest; butterhead is most heat-tolerant of heading types.',
  water: { in: '1–1.5', note: 'Shallow roots require consistent moisture — never let dry out. Mulch around plants to retain moisture and keep roots cool. Water in the morning.' },
  fertilizer: { type: 'High nitrogen', amount: 'Light application — ⅛ cup 10-10-10 per 5 ft row', freq: 'Side-dress nitrogen every 3 weeks for long-season plantings; fast grower that benefits from consistent nitrogen' },
  companions: {
    good: [
      { name: 'Carrots', why: 'Carrots break up soil for lettuce roots; lettuce shades carrot shoulders' },
      { name: 'Radishes', why: 'Interplant as living markers; harvest before lettuce needs space' },
      { name: 'Garlic', why: 'Deters aphids that commonly attack lettuce' },
      { name: 'Strawberries', why: 'Lettuce fills gaps between strawberry plants; compatible root zones' },
      { name: 'Tall crops (corn, tomatoes)', why: 'Provide afternoon shade that prevents bolting in summer' },
    ],
    bad: [
      { name: 'Celery', why: 'Competes aggressively for same nutrients and water' },
      { name: 'Fennel', why: 'Allelopathic to lettuce and most vegetables' },
      { name: 'Parsley', why: 'Some reports of mutual growth inhibition in close proximity' },
    ],
  },
  companionDist: 'Interplant between taller crops (every 6 inches) for space efficiency and natural shading',
  animals: 'Aphids are the main attacker — ladybugs and lacewings are key predators. Slugs and snails are serious problems in cool, wet weather.',
  diseases: [
    { name: 'Downy Mildew', desc: 'Yellow patches on leaves with grey sporulation below. Most common lettuce disease. Apply copper fungicide; improve air circulation; choose resistant varieties.' },
    { name: 'Bottom Rot', desc: 'Slimy brown collapse at base of plant. Caused by Rhizoctonia in wet, warm soil. Avoid overwatering; improve drainage.' },
    { name: 'Tipburn', desc: 'Brown, papery inner leaf edges — calcium deficiency in rapidly growing heads. Water consistently; avoid high humidity; choose tipburn-resistant varieties.' },
  ],
  pests: 'Aphids (insecticidal soap; lady beetles; aluminum foil mulch), slugs and snails (diatomaceous earth; beer traps; copper tape), cabbage looper (Bt spray), leafminers (remove affected leaves; row covers), cutworms (collar around stem).',
  rotation: { family: 'Asteraceae (Aster family)', cycle: 'Rotate every 2–3 years; avoid following endive or chicory in same bed' },
  stages: [
    { label: 'Germinate', title: 'Germination', desc: 'Germinates in 2–8 days at 60–70°F. Seed is dormant above 80°F — refrigerate seed for 24 hours before sowing in heat.' },
    { label: 'Seedling', title: 'Thinning', desc: 'Thin to final spacing when seedlings have 2 true leaves. Thinnings are edible micro-greens.' },
    { label: 'Harvest', title: 'Leaf harvest', desc: 'Begin harvesting outer leaves at 3–4 inches. For heading types, harvest when head feels firm.' },
    { label: 'Bolt', title: 'Bolting', desc: 'Hot weather triggers elongated central stalk and flowering. Flavor becomes bitter. Pull plants and replant in fall.' },
  ],
  nutrition: {
    calories: 15, water: 95.1, protein: 1.4, carbs: 2.9, fiber: 1.3, sugars: 1.2, fat: 0.2,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 166, vitD: 0, vitE: 0.2, vitK: 102,
    vitC: 9.2, vitB1: 0.06, vitB2: 0.06, vitB3: 0.4, vitB5: 0.13, vitB6: 0.07,
    vitB7: 0, vitB9: 73, vitB12: 0, choline: 13.4,
    calcium: 36, phosphorus: 29, magnesium: 13, sodium: 28, potassium: 194, chloride: 0,
    iron: 0.9, zinc: 0.18, copper: 0.03, manganese: 0.25, selenium: 0.6, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Romaine has the highest nutrient density of common lettuce types — significantly more vitamin A and K than iceberg. Red-leaf varieties contain anthocyanins. Good folate source.',
  },
  size: { weight: 'Leaf lettuce: N/A; Romaine: 200–400g; Iceberg: 300–700g per head', dimensions: 'Loose-leaf: 8–12" spread; head types: 6–10" diameter', notes: 'Cut-and-come-again harvesting doubles or triples total yield compared to one-time harvest' },
});
