import Crop from '../Crop.js';
export default new Crop({
  id: 'mint',
  name: 'Mint',
  cat: 'Herb',
  emoji: '🌿',
  planting: {
    zone6: 'Plant divisions or transplants Apr–May; spreads vigorously — contain in pots or with root barriers',
    depth: 'Surface to ½" (transplants at soil level)',
    spacing: '12–18" apart initially; will fill any available space',
    ph: '6.0–7.0',
    sun: 'Full sun to partial shade (afternoon shade improves leaf quality in heat)',
    zone3: 'Hardy perennial; plant May; dies back to roots in winter and re-emerges in spring',
    zone4: 'Plant Apr–May; very cold-hardy',
    zone5: 'Plant Apr',
    zone7: 'Plant Mar–Apr; may stay semi-evergreen',
    zone8: 'Plant Feb–Mar; often stays green through winter',
    zone9: 'Plant Feb–Mar; nearly evergreen; may struggle in summer heat',
  },
  zones: {
    '6': { timing: 'Plant Apr–May; harvest Jun–Sep; cut back in fall; re-emerges Apr', plantingStart: 4, plantingEnd: 5, harvestStart: 6, harvestEnd: 9 },
  },
  special: 'MUST be contained — mint spreads by underground runners (rhizomes) and will take over a garden within 1–2 seasons. Grow in submerged pots or raised beds with buried barriers. Spearmint is mildest; peppermint is strongest; chocolate mint is best for desserts. Harvest before flowering for best flavor. Cut to 2 inches above ground 2–3 times per season.',
  water: { in: '1–2', note: 'Prefers consistently moist soil — does not tolerate drought. Good candidate for areas that stay moist. Water frequently in containers as they dry out faster.' },
  fertilizer: { type: 'Balanced organic (compost or fish emulsion)', amount: 'Light — excess nitrogen reduces essential oil content and flavor', freq: 'Top-dress with compost each spring; no additional feeding needed in good soil' },
  companions: {
    good: [
      { name: 'Tomatoes', why: 'Repels aphids, spider mites, and flea beetles; improves tomato health (keep contained)' },
      { name: 'Cabbage', why: 'Repels cabbage moth, aphids, and flea beetles from brassica beds' },
      { name: 'Peas', why: 'Mint deters aphids that commonly attack peas' },
      { name: 'Blackberries', why: 'Deters ants and aphids; compatible moisture requirements' },
    ],
    bad: [
      { name: 'Parsley', why: 'Mint aggressively out-competes parsley for space and moisture' },
      { name: 'Chamomile', why: 'Some reports of mint inhibiting chamomile germination and growth' },
    ],
  },
  companionDist: 'Always contain in buried pots or root barriers before placing near any companion — spreading mint is worse than no mint',
  animals: 'Excellent pollinator plant when allowed to flower. Strong scent deters deer, rabbits, and mice.',
  diseases: [
    { name: 'Mint Rust', desc: 'Orange-brown pustules on leaves and stems. Most serious mint disease. Remove and destroy all affected growth; cut entire planting to ground and destroy clippings; do not compost. Replant with clean divisions.' },
    { name: 'Verticillium Wilt', desc: 'Wilting and browning despite adequate water. Remove and destroy infected plants. Do not replant mint in same location for 3 years.' },
    { name: 'Powdery Mildew', desc: 'White coating on leaves, especially in fall. Improve air circulation by thinning plants; spray potassium bicarbonate.' },
  ],
  pests: 'Spider mites in hot dry conditions (increase humidity; neem oil), aphids (blast with water; lady beetles), cutworms (collar at base), flea beetles (diatomaceous earth). Generally pest-resistant due to strong scent.',
  rotation: { family: 'Lamiaceae (Mint family)', cycle: 'Perennial; divide every 2–3 years to maintain vigor. Replant divisions in fresh soil.' },
  stages: [
    { label: 'Spring', title: 'Re-emergence', desc: 'New shoots emerge from roots in early Apr. Fresh growth is most flavorful — begin harvesting immediately.' },
    { label: 'Growth', title: 'Rapid spread', desc: 'Grows rapidly in warm weather, sending out underground runners. Monitor container edges or barriers regularly.' },
    { label: 'Harvest', title: 'Active harvest', desc: 'Harvest stems just above a leaf node. Never harvest more than ⅓ of the plant at once. Pinch flower buds as they appear.' },
    { label: 'Cut back', title: 'Midsummer cutback', desc: 'After flowering begins, cut entire planting to 2 inches. Fresh, more flavorful growth returns within 2–3 weeks.' },
    { label: 'Fall', title: 'Dormancy', desc: 'Tops die back after hard frost. Leave roots undisturbed; mulch lightly in zones 3–4.' },
  ],
  nutrition: {
    calories: 70, water: 78.7, protein: 3.8, carbs: 14.9, fiber: 8.0, sugars: 0.2, fat: 0.9,
    saturated: 0.2, monounsat: 0, polyunsat: 0.5,
    vitA: 212, vitD: 0, vitE: 0.9, vitK: 621,
    vitC: 31.8, vitB1: 0.08, vitB2: 0.27, vitB3: 1.7, vitB5: 0.25, vitB6: 0.13,
    vitB7: 0, vitB9: 114, vitB12: 0, choline: 0,
    calcium: 243, phosphorus: 73, magnesium: 80, sodium: 31, potassium: 569, chloride: 0,
    iron: 5.1, zinc: 1.1, copper: 0.33, manganese: 1.18, selenium: 0.7, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Used in small culinary amounts. Exceptionally high vitamin K (621 µg per 100g) and iron. Contains menthol (peppermint) or carvone (spearmint) — the essential oils responsible for flavor and digestive benefits.',
  },
  size: { weight: 'N/A — harvested by stem', dimensions: 'Plants 12–36" tall depending on variety', notes: 'Corsican mint stays under 1 inch tall — ideal for ground cover between stepping stones' },
});
