import Crop from '../Crop.js';
export default new Crop({
  id: 'pawpaw-tree',
  name: 'Pawpaw Tree',
  cat: 'Fruit Tree',
  emoji: '🌳',
  planting: {
    zone6: 'Plant container-grown trees Apr–May; bare-root Mar–Apr before bud break; tap root is fragile — do not disturb',
    depth: 'Crown at soil level; never bury trunk',
    spacing: '15–25 ft apart; plant 2+ genetically distinct trees for cross-pollination',
    ph: '5.5–7.0',
    sun: 'Partial shade when young (first 1–2 years); full sun to partial shade once established',
    zone3: 'Not reliably hardy',
    zone4: 'Marginal; protected sites only; choose hardy selections (Susquehanna, Shenandoah)',
    zone5: 'Plant Apr–May; excellent hardy native fruit',
    zone7: 'Plant Feb–Mar; thrives in heat with moisture',
    zone8: 'Plant Jan–Mar; may struggle in extreme heat; ensure adequate water',
    zone9: 'Not well-adapted; insufficient winter chill',
  },
  zones: {
    '6': { timing: 'Plant Apr–May; harvest Sep–Oct (3–5 years to first fruit from container-grown)', plantingStart: 4, plantingEnd: 5, harvestStart: 9, harvestEnd: 10 },
  },
  special: 'Asimina triloba — the largest edible fruit native to North America. Custard-like tropical flavor (banana-mango-vanilla). MUST have 2 genetically different trees for cross-pollination — clones and seedlings from the same parent will not pollinate each other. Flowers are pollinated by flies and beetles, not bees. Hand-pollinate with a small paintbrush for best yields. Tap root is fragile — never buy bare-root trees more than 18 inches tall; container-grown strongly preferred.',
  water: { in: '1–1.5', note: 'Consistent moisture especially in first 3 years. Tolerates flooding briefly. Drought stress in summer causes early fruit drop. Deep mulching (4–6 inches) is essential to retain moisture and mimic forest floor conditions.' },
  fertilizer: { type: 'Balanced organic — compost and fish emulsion', amount: '2–3 inches compost as mulch each spring', freq: 'Light balanced fertilizer in spring years 1–3; established trees need minimal feeding in good soil' },
  companions: {
    good: [
      { name: 'Comfrey', why: 'Thrives under pawpaw canopy; dynamic accumulator that mimics forest floor nutrient cycling' },
      { name: 'Ramps (Wild Leeks)', why: 'Native woodland companion; shares moist, part-shade preference' },
      { name: 'Spicebush', why: 'Native understory shrub; similar habitat; attracts spicebush swallowtail which also pollinates pawpaw' },
    ],
    bad: [
      { name: 'Grass lawn', why: 'Lawn grass competes aggressively with shallow feeder roots; mowing equipment injures trunk' },
    ],
  },
  companionDist: 'Mulch ring minimum 3 ft radius; plant companions outside drip line; pawpaw spreads via root suckers to form a colony — allow or mow suckers depending on goals',
  animals: 'Flowers pollinated by flies and carrion beetles (attracted to the faintly fetid smell). Zebra swallowtail butterfly larvae feed exclusively on pawpaw leaves — excellent host plant. Fruit eaten by raccoons, opossums, foxes, and black bears.',
  diseases: [
    { name: 'Pawpaw Bunch Disease', desc: 'Abnormal clustering of leaves and stunted shoots; spread by leafhoppers. No cure — remove and destroy infected trees. Rare in well-managed gardens.' },
    { name: 'Leaf Spot', desc: 'Brown spots on leaves in wet seasons. Usually cosmetic. Rake and destroy fallen leaves.' },
  ],
  pests: 'Remarkably pest-resistant — pawpaw contains acetogenins (natural insecticides) in bark, leaves, and seeds. Pawpaw peduncle borer (small caterpillar in fruit stem; hand-remove), birds and mammals (netting or prompt harvest as fruit ripens).',
  rotation: { family: 'Annonaceae (Custard Apple family)', cycle: 'Permanent native fruit tree — 50+ year lifespan. Only North American member of a largely tropical family.' },
  stages: [
    { label: 'Yr 1–2', title: 'Slow establishment', desc: 'Very slow top growth in years 1–2 — energy goes to deep tap root. Do not panic; provide shade cloth and consistent moisture.' },
    { label: 'Yr 3–5', title: 'Accelerated growth', desc: 'Once tap root established, rapid growth begins. Tree can grow 1–2 ft per year. Shade cloth can be removed.' },
    { label: 'Spring', title: 'Unique flowers', desc: 'Dark maroon, 6-petaled flowers appear Apr–May before leaves. Hand-pollinate by transferring pollen between trees with a paintbrush for reliable fruit set.' },
    { label: 'Sep–Oct', title: 'Fruit ripening', desc: 'Fruit turns from green to yellow-green and yields to gentle pressure when ripe. Falls from tree when fully ripe. Harvest slightly underripe and ripen indoors 3–5 days.' },
  ],
  nutrition: {
    calories: 80, water: 74.9, protein: 1.2, carbs: 18.8, fiber: 2.6, sugars: 0, fat: 1.2,
    saturated: 0, monounsat: 0, polyunsat: 0,
    vitA: 0, vitD: 0, vitE: 0, vitK: 0,
    vitC: 18.3, vitB1: 0, vitB2: 0, vitB3: 0, vitB5: 0, vitB6: 0,
    vitB7: 0, vitB9: 0, vitB12: 0, choline: 0,
    calcium: 63, phosphorus: 47, magnesium: 113, sodium: 0, potassium: 345, chloride: 0,
    iron: 0.9, zinc: 0, copper: 0, manganese: 0, selenium: 0, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Exceptionally high magnesium (113 mg per 100g) and potassium for a fruit. Good vitamin C and iron. Nutritional data is limited — one of the least-studied native fruits. Seeds contain acetogenins and are NOT edible.',
  },
  size: { weight: '100–500g per fruit', dimensions: '3–6" long, 2–3" wide; kidney or mango shaped', notes: 'Named varieties (Shenandoah, Susquehanna, Mango) produce larger, sweeter fruit than wild seedlings' },
});
