import Crop from '../Crop.js';
export default new Crop({
  id: 'pear-tree',
  name: 'Pear Tree',
  cat: 'Fruit Tree',
  emoji: '🍐',
  planting: {
    zone6: 'Plant bare-root Mar–Apr before bud break; container-grown through May',
    depth: 'Crown at soil level; graft union 2 inches above soil',
    spacing: 'Standard: 20–25 ft; semi-dwarf: 12–15 ft; dwarf: 8–10 ft',
    ph: '6.0–7.0',
    sun: 'Full sun (6–8 hours)',
    zone3: 'Ussurian pear (Pyrus ussuriensis) or Summercrisp variety; plant May',
    zone4: 'Summercrisp, Luscious, Patten; plant late Apr–May',
    zone5: 'Most European pears; plant Apr',
    zone7: 'Plant Feb–Mar; excellent fire blight pressure — choose resistant varieties',
    zone8: 'Plant Jan–Feb; Orient, Kieffer (fire blight resistant); Flordahome',
    zone9: 'Plant Dec–Jan; low-chill Asian pears',
  },
  zones: {
    '6': { timing: 'Plant Mar–Apr; bloom Apr; harvest Aug–Oct depending on variety', plantingStart: 3, plantingEnd: 4, harvestStart: 8, harvestEnd: 10 },
  },
  special: 'Most European pears require a cross-pollinating partner (Bartlett + Bosc is a classic pair). Harvest pears BEFORE fully ripe — pears ripen from the inside out and turn grainy if left on tree. Bartlett turns yellow when ready; others must be tested by tilting fruit — it should come away easily. Ripen at room temperature for 3–7 days. Fire blight is the primary disease threat in zones 5–7.',
  water: { in: '1', note: 'Deep watering once a week. Consistent moisture during fruit development. Avoid waterlogging — pears are susceptible to root rot. Drip irrigation preferred.' },
  fertilizer: { type: 'Balanced; very low nitrogen once bearing', amount: '½ lb 10-10-10 per year of tree age up to 5 lbs', freq: 'Once in early spring; AVOID excess nitrogen — overly lush growth is highly susceptible to fire blight' },
  companions: {
    good: [
      { name: 'Marigolds', why: 'Deter aphids and codling moth at the base of the tree' },
      { name: 'Chives', why: 'Planted around base reportedly reduces fire blight and scab pressure' },
      { name: 'Comfrey', why: 'Dynamic mineral accumulator; deep roots bring up potassium and calcium' },
      { name: 'Nasturtiums', why: 'Trap crop for aphids; attract beneficial predatory insects' },
    ],
    bad: [
      { name: 'Potatoes', why: 'Share blight pathogens; avoid planting near pear roots' },
      { name: 'Juniper', why: 'Hosts pear rust (Gymnosporangium fuscum); remove nearby junipers or choose rust-resistant varieties' },
    ],
  },
  companionDist: 'Grass-free ring of 3 ft around trunk; wood chip mulch; plant companions at drip line',
  animals: 'Bees essential for cross-pollination. Codling moth is controlled by trichogramma wasps. Birds eat overripe fallen fruit — helps reduce pest overwintering sites.',
  diseases: [
    { name: 'Fire Blight', desc: 'Most serious pear disease. Shoot tips turn black as if burned; bacterial ooze in wet weather. Prune 12 inches below infection with sterilized tools; avoid excess nitrogen; choose resistant varieties (Harrow Sweet, Moonglow, Kieffer).' },
    { name: 'Pear Scab', desc: 'Olive-brown scabby patches on fruit and leaves. Spray copper or sulfur from bud break; remove fallen leaves; choose resistant varieties.' },
    { name: 'Fabraea Leaf Spot', desc: 'Dark spots on leaves causing early defoliation. Rake leaves; copper spray in spring.' },
  ],
  pests: 'Codling moth (pheromone traps; kaolin clay; spinosad), pear psylla (most serious pear pest in the East — horticultural oil at dormant stage; predatory insects), aphids (horticultural oil at bud swell; insecticidal soap), stinkbugs (exclusion netting).',
  rotation: { family: 'Rosaceae (Pyrus genus)', cycle: 'Permanent tree — 25–50+ year productive life. Do not replant in old pear/apple site.' },
  stages: [
    { label: 'Dormant', title: 'Winter pruning', desc: 'Prune in late Feb–Mar to open canopy and remove fire blight-susceptible water sprouts. Pears trained to central leader resist blight better.' },
    { label: 'Bloom', title: 'Early spring bloom', desc: 'White flowers appear early Apr — one of the first fruit trees to bloom. Frost risk is high; protect with frost cloth if temps below 28°F are forecast during bloom.' },
    { label: 'Fruit set', title: 'Fruitlet thinning', desc: 'Thin to one fruit per 6-inch cluster in Jun for large, quality pears.' },
    { label: 'Harvest', title: 'Pre-ripe harvest', desc: 'Harvest before fully ripe. Test: tilt fruit — if it separates easily, it\'s ready. Ripen at room temperature. Refrigerate to slow ripening.' },
  ],
  nutrition: {
    calories: 57, water: 83.7, protein: 0.4, carbs: 15.2, fiber: 3.1, sugars: 9.8, fat: 0.1,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 1, vitD: 0, vitE: 0.1, vitK: 4.4,
    vitC: 4.2, vitB1: 0.01, vitB2: 0.03, vitB3: 0.2, vitB5: 0.05, vitB6: 0.03,
    vitB7: 0, vitB9: 7, vitB12: 0, choline: 5.1,
    calcium: 9, phosphorus: 12, magnesium: 7, sodium: 1, potassium: 116, chloride: 0,
    iron: 0.2, zinc: 0.1, copper: 0.08, manganese: 0.05, selenium: 0.1, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 2.2,
    notes: 'Good source of dietary fiber, particularly pectin. Contains arbutin, a natural compound. Pears are one of the least allergenic fruits — often recommended as first fruit for infants.',
  },
  size: { weight: '100–250g per fruit', dimensions: '2.5–4" long, 2–3" diameter', notes: 'Asian pears are round and crisp (apple-like); European pears are soft and buttery when ripe' },
});
