import Crop from '../Crop.js';
export default new Crop({
  id: 'peppers',
  name: 'Peppers',
  cat: 'Fruiting Veg',
  emoji: '🫑',
  planting: {
    zone6: 'Start indoors Mar (8–10 weeks before last frost); transplant late May when nights stay above 55°F',
    depth: '¼" (seed); transplant 1–2" deeper than nursery depth',
    spacing: '18–24" apart in rows 24" wide',
    ph: '6.0–6.8',
    sun: 'Full sun (8+ hours)',
    zone3: 'Start indoors Apr; transplant Jun; choose fast-maturing varieties',
    zone4: 'Start indoors late Mar; transplant late May–early Jun',
    zone5: 'Start indoors mid-Mar; transplant mid-May',
    zone7: 'Start indoors Feb; transplant Apr',
    zone8: 'Start indoors Jan; transplant Mar; perennial in mild winters',
    zone9: 'Start indoors Jan or direct sow Feb; often behaves as perennial',
  },
  zones: {
    '6': { timing: 'Transplant late May; harvest Jul–Oct (70–90 days from transplant for bells)', plantingStart: 5, plantingEnd: 6, harvestStart: 7, harvestEnd: 10 },
  },
  special: 'Peppers need warm nights (above 55°F) to set fruit — cold nights cause blossom drop. Start seed at 80–85°F bottom heat. Do not rush transplanting. Mature peppers (red, orange, yellow bells) are sweeter and more nutritious than green — just earlier picked. Hot peppers: capsaicin increases in drier, hotter conditions.',
  water: { in: '1–1.5', note: 'Consistent moisture — drought stress causes blossom drop and bitter flavor. Increase watering during fruit development. Avoid wetting foliage to prevent bacterial spot.' },
  fertilizer: { type: 'Balanced then low nitrogen at fruiting', amount: '2 tbsp 10-10-10 per transplant hole', freq: 'Light nitrogen at transplanting; switch to high phosphorus/potassium (5-10-10) once flowering begins to maximize fruit set over foliage' },
  companions: {
    good: [
      { name: 'Basil', why: 'Repels aphids, spider mites, and thrips; may improve pepper flavor' },
      { name: 'Tomatoes', why: 'Same growing conditions; both benefit from shared row cover or wind protection' },
      { name: 'Marigolds', why: 'Deter aphids, nematodes, and whiteflies' },
      { name: 'Carrots', why: 'Loose carrot roots aerate soil around pepper roots; no resource competition' },
      { name: 'Corn', why: 'Provides windbreak in exposed sites; peppers hate wind' },
    ],
    bad: [
      { name: 'Fennel', why: 'Allelopathic to most vegetables including peppers' },
      { name: 'Kohlrabi', why: 'Some reports of mutual inhibition between peppers and kohlrabi' },
    ],
  },
  companionDist: 'Plant basil every 18 inches between pepper plants for maximum benefit',
  animals: 'Bees and other pollinators visit pepper flowers. Self-pollinating but insect activity improves fruit set.',
  diseases: [
    { name: 'Bacterial Spot', desc: 'Water-soaked spots on leaves and fruit turning brown with yellow halos. Most common in warm, wet conditions. Use disease-free transplants; avoid overhead watering; copper spray preventively.' },
    { name: 'Phytophthora Blight', desc: 'Rapid wilting and collapse of entire plant; dark brown lesions at base. No cure — remove plants; improve drainage; do not replant peppers or tomatoes in same spot for 4+ years.' },
    { name: 'Anthracnose', desc: 'Sunken dark spots on ripe fruit. Use disease-free seed; harvest promptly; copper spray.' },
    { name: 'Mosaic Virus', desc: 'Mottled, distorted leaves; reduced yield. Spread by aphids. No cure — remove plant; control aphids; use reflective mulch.' },
  ],
  pests: 'Aphids (insecticidal soap; neem; reflective mulch), pepper weevil (in southern zones — pyrethrin; crop rotation), European corn borer (Bt spray), thrips (spinosad; blue sticky traps), pepper maggot fly (row covers; yellow sticky traps).',
  rotation: { family: 'Solanaceae (Nightshade family)', cycle: 'Rotate every 3–4 years; do not follow tomatoes, eggplant, or potatoes in same bed' },
  stages: [
    { label: 'Seedling', title: 'Indoor start', desc: 'Slow to germinate (10–21 days) and grow. Bottom heat at 80°F speeds germination. Harden off over 10–14 days before transplanting.' },
    { label: 'Transplant', title: 'Establishment', desc: 'Peppers are slow to establish. Protect from cold nights with row cover. Growth accelerates when nights consistently above 60°F.' },
    { label: 'Bloom', title: 'Flowering', desc: 'Small white flowers are self-pollinating. Shake plants gently or use electric toothbrush to improve pollination in still air.' },
    { label: 'Green fruit', title: 'Immature fruit', desc: 'Green peppers are mature but not fully ripe. Harvest some green to encourage continued production.' },
    { label: 'Color', title: 'Full ripening', desc: 'Red/orange/yellow/purple peppers are fully ripe — sweeter, more vitamin C, more antioxidants than green stage.' },
  ],
  nutrition: {
    calories: 31, water: 92.7, protein: 1.0, carbs: 6.0, fiber: 2.1, sugars: 4.2, fat: 0.3,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 157, vitD: 0, vitE: 1.6, vitK: 7.4,
    vitC: 127.7, vitB1: 0.06, vitB2: 0.06, vitB3: 1.0, vitB5: 0.32, vitB6: 0.29,
    vitB7: 0, vitB9: 46, vitB12: 0, choline: 5.5,
    calcium: 7, phosphorus: 26, magnesium: 12, sodium: 4, potassium: 211, chloride: 0,
    iron: 0.4, zinc: 0.25, copper: 0.02, manganese: 0.12, selenium: 0.1, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Values for red bell pepper — one of the highest vitamin C foods (127 mg per 100g, more than oranges). Red peppers have 3x more vitamin C than green. Capsaicin in hot peppers has anti-inflammatory and metabolism-boosting properties.',
  },
  size: { weight: '100–200g per bell pepper', dimensions: '3–4" long, 3" wide (bell type)', notes: 'Hot varieties vary enormously in size from tiny Thai peppers (1 cm) to large Anaheim (8 inches)' },
});
