import Crop from '../Crop.js';
export default new Crop({
  id: 'pokeweed',
  name: 'Pokeweed',
  cat: 'Wild Edible',
  emoji: '🌿',
  planting: {
    zone6: 'Naturalizes readily — self-sows prolifically. If transplanting, move small seedlings in early spring before tap root deepens.',
    depth: '½" if direct sowing saved seed',
    spacing: 'Allow 4–6 ft per plant — becomes very large',
    ph: '5.5–7.0',
    sun: 'Full sun to partial shade',
    zone3: 'Not reliably hardy; dies back to roots',
    zone4: 'Dies back to roots in winter; re-emerges from deep root',
    zone5: 'Perennial from root; very vigorous',
    zone7: 'Thrives; highly productive',
    zone8: 'Thrives; large plants',
    zone9: 'Thrives; nearly evergreen in warmest areas',
  },
  zones: {
    '6': { timing: 'Perennial; new shoots emerge Apr–May; harvest shoots Apr–May only; berries ripen Aug–Sep', plantingStart: 4, plantingEnd: 5, harvestStart: 4, harvestEnd: 5 },
  },
  special: '⚠️ TOXICITY WARNING: ALL parts of pokeweed are toxic raw. The ROOT is extremely toxic and should never be eaten. Berries are toxic especially to children. Young shoots (under 6 inches, before any pink coloration) can be made edible by boiling in THREE changes of water — a traditional Appalachian practice ("poke sallet"). Only harvest shoots before any purple/pink coloration appears. Do not plant where children play. Considered both a valuable native plant and a serious weed.',
  water: { in: '0.5', note: 'Drought-tolerant deep-rooted perennial. No irrigation needed once established.' },
  fertilizer: { type: 'None required', amount: 'N/A', freq: 'Wild native plant; no fertilization needed or recommended' },
  companions: {
    good: [
      { name: 'Elderberries', why: 'Both are large native shrubs for naturalistic or food forest plantings; similar habitat' },
      { name: 'Wild Blackberries', why: 'Co-occur naturally at woodland edges; compatible growth habit' },
    ],
    bad: [
      { name: 'Vegetable garden', why: 'Self-seeds aggressively; toxic root is nearly impossible to fully remove once established; do not allow in production beds' },
    ],
  },
  companionDist: 'Plant only in wild areas, food forests, or naturalistic gardens where toxicity risk is managed and spread can be controlled',
  animals: 'Berries eaten by 33+ bird species including mourning doves, mockingbirds, and catbirds — birds are immune to the toxins. Important late-season wildlife food source. Host plant for various moth species.',
  diseases: [
    { name: 'Leaf Spot', desc: 'Various fungal spots on leaves. Usually cosmetic on this vigorous plant.' },
  ],
  pests: 'Virtually pest-free due to plant toxins. Deer occasionally browse young shoots but usually avoid it.',
  rotation: { family: 'Phytolaccaceae', cycle: 'Deep-rooted perennial — essentially permanent once established. The massive taproot can be 6+ feet deep and nearly impossible to fully remove.' },
  stages: [
    { label: 'Spring', title: 'Edible shoot emergence', desc: 'New shoots emerge Apr–May from the large perennial root. Harvest ONLY shoots under 6 inches and before any pink color appears. Boil in 3 changes of water before eating.' },
    { label: 'Summer', title: 'Rapid growth', desc: 'Plants grow to 6–10 feet with hollow, purple-red stems. Deeply lobed leaves. Impressive architectural plant.' },
    { label: 'Late summer', title: 'Flowering', desc: 'Long racemes of small white flowers appear Jul–Aug.' },
    { label: 'Fall', title: 'Berry production', desc: 'Dark purple-black berries in pendulous clusters ripen Aug–Sep. Highly attractive to birds. TOXIC to humans.' },
  ],
  nutrition: {
    calories: 0, water: 0, protein: 0, carbs: 0, fiber: 0, sugars: 0, fat: 0,
    saturated: 0, monounsat: 0, polyunsat: 0,
    vitA: 0, vitD: 0, vitE: 0, vitK: 0,
    vitC: 0, vitB1: 0, vitB2: 0, vitB3: 0, vitB5: 0, vitB6: 0,
    vitB7: 0, vitB9: 0, vitB12: 0, choline: 0,
    calcium: 0, phosphorus: 0, magnesium: 0, sodium: 0, potassium: 0, chloride: 0,
    iron: 0, zinc: 0, copper: 0, manganese: 0, selenium: 0, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: '⚠️ ALL PARTS ARE TOXIC RAW — root especially. Only properly prepared (triple-boiled) young shoots are edible by traditional preparation. Not recommended for casual consumption. Grown primarily for wildlife value and naturalistic gardens.',
  },
  size: { weight: 'N/A', dimensions: 'Plants 6–10 ft tall, 4–6 ft wide; root can extend 6+ ft deep', notes: 'One of the most architecturally striking native plants; bold textural statement in naturalistic landscapes' },
});
