import Crop from '../Crop.js';
export default new Crop({
  id: 'red-onions',
  name: 'Red Onions',
  cat: 'Allium',
  emoji: '🧅',
  planting: {
    zone6: 'Start indoors Jan–Feb (10–12 weeks before last frost); transplant Apr–early May; or plant sets late Apr',
    depth: '¼" (seed); sets just below surface with neck pointing up',
    spacing: '4–6" apart for bulbs; 2–3" for scallions; rows 12–18" wide',
    ph: '6.0–7.0',
    sun: 'Full sun (6–8 hours)',
    zone3: 'Plant sets mid-May; short-day varieties may not bulb well; try intermediate-day varieties',
    zone4: 'Plant transplants or sets early May',
    zone5: 'Plant transplants Apr; sets late Apr',
    zone7: 'Plant transplants Mar–Apr; fall planting of sets possible',
    zone8: 'Plant Oct–Nov for spring harvest; short-day varieties (Burgundy, Red Creole)',
    zone9: 'Plant Oct–Jan; short-day varieties only',
  },
  zones: {
    '6': { timing: 'Transplant Apr–May; harvest late Jul–Aug when tops fall over', plantingStart: 4, plantingEnd: 5, harvestStart: 7, harvestEnd: 8 },
  },
  special: 'Onion bulbing is triggered by day length — zone 6 requires intermediate-day (12–14 hour) varieties. Long-day varieties (14+ hours) are for zones 3–5; short-day for zones 8–9. Red candy is an excellent intermediate-day red onion for zone 6. Bulbs stop growing when tops fall over — do not force them. Cure 3–4 weeks in a dry, airy location. Red onions do not store as long as yellow/white types.',
  water: { in: '1', note: 'Consistent moisture during bulb development. Stop watering when tops begin to fall. Wet soil at harvest causes neck rot in storage.' },
  fertilizer: { type: 'High nitrogen early; taper off as bulbs enlarge', amount: '½ cup 10-10-10 per 10-ft row at planting', freq: 'Side-dress with nitrogen when plants are 6 inches tall; reduce nitrogen as bulbs swell in Jun; stop all fertilizing by Jul 1' },
  companions: {
    good: [
      { name: 'Carrots', why: 'Classic mutual deterrence — onion scent repels carrot fly; carrot scent repels onion fly' },
      { name: 'Tomatoes', why: 'Onions deter aphids, spider mites, and onion fly near tomatoes' },
      { name: 'Lettuce', why: 'Onions deter aphids; both have shallow root systems that don\'t compete' },
      { name: 'Brassicas', why: 'Onion scent deters cabbage moths and aphids from kale, cabbage, broccoli' },
      { name: 'Strawberries', why: 'Repel spider mites and aphids from strawberry beds' },
    ],
    bad: [
      { name: 'Beans', why: 'All alliums severely inhibit bean growth — strict separation required' },
      { name: 'Peas', why: 'Same allium-legume incompatibility' },
      { name: 'Asparagus', why: 'Competes and inhibits asparagus development' },
      { name: 'Sage', why: 'Sage inhibits onion growth — keep separated' },
    ],
  },
  companionDist: 'Interplant onions within carrot rows every 4 inches for maximum pest deterrence — the ideal bed combination',
  animals: 'Deer and rabbit repellent. Strong allium scent deters many small mammals.',
  diseases: [
    { name: 'Downy Mildew', desc: 'Pale spots on leaves; grey-purple sporulation. Spreads rapidly in cool wet conditions. Apply copper fungicide preventively; improve air circulation; water in morning.' },
    { name: 'Botrytis Neck Rot', desc: 'Common storage disease. Grey mold at neck of harvested bulbs. Ensure thorough curing (3–4 weeks); store in dry conditions; avoid storing any bulbs with soft necks.' },
    { name: 'Fusarium Basal Rot', desc: 'Pink-white rot at bulb base; roots collapse. Plant in well-drained soil; long rotation (4+ years between allium crops in same bed).' },
    { name: 'Smut', desc: 'Dark streaks in leaves; black powdery spores. Destroy infected plants; long rotation.' },
  ],
  pests: 'Onion thrips (most common — spinosad or neem; avoid drought stress; reflective mulch), onion maggot (row covers; crop rotation; plant sets rather than transplants in heavily infested soil), onion leaf miner (row covers).',
  rotation: { family: 'Amaryllidaceae (Allium genus)', cycle: 'Rotate every 3–4 years; do not follow garlic, leeks, shallots, or chives in same bed' },
  stages: [
    { label: 'Seedling', title: 'Transplant establishment', desc: 'Transplants look fragile but establish quickly. Keep moist for first 2 weeks. Weed carefully — shallow allium roots are easily disturbed.' },
    { label: 'Growth', title: 'Bulb initiation', desc: 'Day length triggers bulbing when critical threshold is met. Do not push nitrogen — bulbs should be swelling, not growing taller.' },
    { label: 'Bulb fill', title: 'Rapid enlargement', desc: 'Bulbs swell rapidly Jun–Jul. Maintain consistent watering. Stop nitrogen fertilizing.' },
    { label: 'Topple', title: 'Tops fall over', desc: 'When 50–75% of tops have fallen naturally, bulbs are mature. Do not force tops down. Stop watering.' },
    { label: 'Cure', title: 'Curing', desc: 'Pull bulbs and cure in a single layer in a dry, airy, shaded location for 3–4 weeks. Neck must be completely dry before storage.' },
  ],
  nutrition: {
    calories: 40, water: 89.1, protein: 1.1, carbs: 9.3, fiber: 1.7, sugars: 4.2, fat: 0.1,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 0, vitD: 0, vitE: 0.1, vitK: 0.4,
    vitC: 7.4, vitB1: 0.05, vitB2: 0.03, vitB3: 0.1, vitB5: 0.12, vitB6: 0.12,
    vitB7: 0, vitB9: 19, vitB12: 0, choline: 6.1,
    calcium: 23, phosphorus: 29, magnesium: 10, sodium: 4, potassium: 146, chloride: 0,
    iron: 0.2, zinc: 0.17, copper: 0.04, manganese: 0.13, selenium: 0.5, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Red onions contain significantly more anthocyanins (quercetin, anthocyanin) than yellow or white onions. These powerful antioxidants are largely destroyed by cooking — eat some raw for maximum benefit. Quercetin has anti-inflammatory and cardiovascular protective properties.',
  },
  size: { weight: '100–250g per bulb', dimensions: '2–3.5" diameter', notes: 'Red Candy, Red Burgermaster, and Redwing are top intermediate-day varieties for zones 5–7' },
});
