import Crop from '../Crop.js';
export default new Crop({
  id: 'rosemary',
  name: 'Rosemary',
  cat: 'Herb',
  emoji: '🌿',
  planting: {
    zone6: 'Transplant May after last frost; treat as annual or bring indoors in winter in zone 6 (barely hardy)',
    depth: 'Transplant at nursery soil level',
    spacing: '24–36" apart (mature shrub is large)',
    ph: '6.0–7.0',
    sun: 'Full sun (8+ hours — essential)',
    zone3: 'Annual only; start indoors Apr; bring in before frost',
    zone4: 'Annual only; treat same as zone 3',
    zone5: 'Annual or overwinter in unheated garage; Arp variety is most cold-hardy',
    zone7: 'Perennial; may die back in hard winters; Arp and Madelene Hill are most cold-hardy',
    zone8: 'Perennial; thrives; excellent landscape shrub',
    zone9: 'Perennial; thrives; drought-tolerant once established',
  },
  zones: {
    '6': { timing: 'Transplant May; harvest Jun–Oct; bring indoors before hard frost or treat as annual', plantingStart: 5, plantingEnd: 6, harvestStart: 6, harvestEnd: 10 },
  },
  special: 'In zone 6, rosemary is borderline hardy (dies at sustained temperatures below 10°F). The Arp variety is the most cold-hardy cultivar and survives zone 6 winters with heavy mulching and a sheltered south-facing location. Container growing allows bringing indoors: give a south-facing window and keep soil on the dry side in winter. Do not overwater — rosemary rots extremely easily in wet soil.',
  water: { in: '0.5', note: 'Drought-tolerant Mediterranean herb — prefers dry conditions. Allow soil to dry completely between waterings. The most common way to kill rosemary is overwatering. Excellent drainage is essential.' },
  fertilizer: { type: 'Minimal — light balanced slow-release', amount: 'Very light — excess fertilizer reduces aromatic oil concentration', freq: 'Single light application of slow-release balanced fertilizer in spring; no additional feeding' },
  companions: {
    good: [
      { name: 'Carrots', why: 'Rosemary scent confuses carrot fly; improves carrot flavor according to some growers' },
      { name: 'Cabbage', why: 'Strong scent deters cabbage moth egg-laying' },
      { name: 'Beans', why: 'Repels Mexican bean beetle (one of few herbs that benefits legumes)' },
      { name: 'Sage', why: 'Compatible Mediterranean companions with same growing requirements' },
      { name: 'Marigolds', why: 'Combined pest-deterrent effect in vegetable garden borders' },
    ],
    bad: [
      { name: 'Basil', why: 'Conflicting moisture needs — basil wants consistent moisture; rosemary wants dry conditions' },
      { name: 'Mint', why: 'Mint requires more moisture and will compete aggressively' },
      { name: 'Cucumbers', why: 'Different moisture requirements; rosemary stressed by cucumber irrigation schedule' },
    ],
  },
  companionDist: 'Excellent border plant at the dry edge of herb and vegetable gardens; 24-inch spacing from moisture-loving herbs',
  animals: 'Excellent pollinator plant — flowers attract bees heavily when in bloom (late spring in zones 7–9). Deer and rabbit resistant.',
  diseases: [
    { name: 'Root Rot (Phytophthora)', desc: 'Most common rosemary problem — caused entirely by overwatering or poor drainage. Leaves turn brown from base up; roots mushy. No recovery. Ensure perfect drainage; treat soil as desert-like.' },
    { name: 'Powdery Mildew', desc: 'White coating on leaves in humid conditions. Improve air circulation; reduce humidity around plant; apply potassium bicarbonate.' },
    { name: 'Botrytis', desc: 'Grey mold in wet, cool conditions. Improve air circulation; avoid overwatering.' },
  ],
  pests: 'Generally pest-resistant due to aromatic oils. Rosemary beetle (metallic green/purple beetle; hand-pick; pyrethrin), aphids in containers (insecticidal soap), spider mites when stressed by drought or dry indoor air (mist leaves; neem oil).',
  rotation: { family: 'Lamiaceae (Mint family)', cycle: 'Perennial in zones 7–9; annual or container plant in zone 6 and colder. Refresh container plants every 2–3 years with fresh potting mix.' },
  stages: [
    { label: 'Spring', title: 'New growth flush', desc: 'Fresh silvery-green new growth appears in spring. Best time for soft tip cuttings to propagate new plants.' },
    { label: 'Summer', title: 'Active harvest', desc: 'Harvest 2–4 inch stem tips regularly throughout summer. Frequent harvesting keeps plant compact and productive. Never cut into old woody stems — they rarely re-sprout.' },
    { label: 'Fall', title: 'Pre-frost preparation', desc: 'In zone 6: mulch heavily with straw; move containers indoors before first hard frost. Reduce watering indoors significantly.' },
    { label: 'Winter', title: 'Indoor care', desc: 'Indoors: south window, cool temperature (50–65°F preferred), minimal water, good air circulation. Watch for spider mites in dry indoor air.' },
  ],
  nutrition: {
    calories: 131, water: 67.8, protein: 3.3, carbs: 20.7, fiber: 14.1, sugars: 0, fat: 5.9,
    saturated: 2.8, monounsat: 1.2, polyunsat: 0.9,
    vitA: 146, vitD: 0, vitE: 0.4, vitK: 0,
    vitC: 21.8, vitB1: 0.04, vitB2: 0.15, vitB3: 0.9, vitB5: 0.8, vitB6: 0.34,
    vitB7: 0, vitB9: 109, vitB12: 0, choline: 0,
    calcium: 317, phosphorus: 66, magnesium: 91, sodium: 26, potassium: 668, chloride: 0,
    iron: 6.7, zinc: 0.93, copper: 0.3, manganese: 0.96, selenium: 0, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Used in small culinary amounts. Very high iron (6.7 mg per 100g), calcium, and potassium for an herb. Contains rosmarinic acid, carnosic acid, and carnosol — potent antioxidants with neuroprotective and anti-inflammatory properties.',
  },
  size: { weight: 'N/A — harvested by stem', dimensions: 'Upright varieties: 3–6 ft tall and wide; trailing varieties: 1–2 ft tall, 4–8 ft spread', notes: 'Arp and Madelene Hill are most cold-hardy; Tuscan Blue has strongest culinary flavor; trailing types excellent for walls' },
});
