import Crop from '../Crop.js';
export default new Crop({
  id: 'spinach',
  name: 'Spinach',
  cat: 'Leafy Green',
  emoji: '🥬',
  planting: {
    zone6: 'Spring: direct sow Mar–Apr (4–6 weeks before last frost). Fall: direct sow Aug–Sep for harvest until hard freeze.',
    depth: '½"',
    spacing: '4–6" apart after thinning; rows 12" wide',
    ph: '6.5–7.0',
    sun: 'Full sun in spring; partial shade in summer (bolts in heat and long days)',
    zone3: 'Direct sow mid-May to Jun; short spring window only',
    zone4: 'Direct sow May; fall sow late Jul',
    zone5: 'Direct sow Apr; fall sow early Aug',
    zone7: 'Direct sow Feb–Mar; fall sow Sep–Oct; overwinters with light protection',
    zone8: 'Fall–winter–spring crop; sow Sep–Feb; overwinters without protection',
    zone9: 'Fall–spring crop; sow Oct–Mar',
  },
  zones: {
    '6': { timing: 'Sow Mar–Apr; harvest Apr–May. Fall sow Aug–Sep; harvest Sep–Nov', plantingStart: 3, plantingEnd: 4, harvestStart: 4, harvestEnd: 11 },
  },
  special: 'Bolts (goes to seed) quickly when days exceed 14 hours and temperatures exceed 75°F — spring window is short in zone 6. Savoy types (Bloomsdale) are slower to bolt and more cold-hardy. Baby spinach harvested at 3–4 weeks. Fall spinach is sweeter and more productive than spring. Mulch fall spinach and it may overwinter for early spring harvest.',
  water: { in: '1–1.5', note: 'Consistent moisture is essential — drought stress triggers bolting. Mulch to keep roots cool and moist. Water in morning to prevent overnight leaf wetness.' },
  fertilizer: { type: 'High nitrogen', amount: '⅛ cup 10-10-10 per 5 ft row', freq: 'At planting and side-dress nitrogen at 3 weeks; spinach is a heavy but fast nitrogen consumer' },
  companions: {
    good: [
      { name: 'Strawberries', why: 'Spinach provides living mulch around strawberry crowns; both are cool-season crops' },
      { name: 'Radishes', why: 'Interplant as pest trap crop and row markers; harvest radishes before spinach needs space' },
      { name: 'Peas', why: 'Peas provide gentle shade that extends spinach season; fix nitrogen' },
      { name: 'Garlic', why: 'Deters aphids that commonly attack spinach' },
      { name: 'Corn (as shade)', why: 'Grow spinach on north side of established corn for summer shade that prevents bolting' },
    ],
    bad: [
      { name: 'Fennel', why: 'Allelopathic to most vegetables including spinach' },
      { name: 'Potatoes', why: 'Compete heavily for same nutrients; different pest pressures interact' },
    ],
  },
  companionDist: 'Interplant with radishes every 4 inches within rows; radish harvest opens space for spinach to spread',
  animals: 'Aphids are the main pest — ladybugs and lacewings are key. Slugs are significant problem in cool, moist conditions.',
  diseases: [
    { name: 'Downy Mildew', desc: 'Most serious spinach disease. Yellow patches on upper leaf; grey-purple sporulation below. Apply copper fungicide; choose resistant varieties (Tyee, Catalina); improve air circulation.' },
    { name: 'Fusarium Wilt', desc: 'Yellowing and wilting despite moisture. No cure. Long rotation (3+ years); choose resistant varieties.' },
    { name: 'White Rust', desc: 'White blister-like pustules on leaves. More cosmetic than destructive. Copper spray; crop rotation.' },
  ],
  pests: 'Aphids (insecticidal soap; reflective mulch; lady beetles), leafminers (remove and destroy affected leaves; row covers), slugs (diatomaceous earth; beer traps; copper tape), flea beetles (row covers especially at fall planting).',
  rotation: { family: 'Amaranthaceae (Chenopodiaceae) — same family as beets and chard', cycle: 'Rotate every 2–3 years; do not follow beets or chard in same bed (share downy mildew races)' },
  stages: [
    { label: 'Germinate', title: 'Germination', desc: 'Germinates in 7–14 days; fastest at 50–65°F. Will germinate in near-freezing conditions — plant early.' },
    { label: 'Thin', title: 'Thinning', desc: 'Thin to 4–6 inches when seedlings are 2 inches tall. Thinnings are edible.' },
    { label: 'Harvest', title: 'Leaf harvest', desc: 'Begin harvesting outer leaves when 4–6 leaves present. For baby spinach, cut entire plant at 3 inches above soil and allow regrowth.' },
    { label: 'Bolt', title: 'Bolting', desc: 'Central stalk elongates rapidly in heat or long days. Flavor turns bitter. Pull and replant for fall, or let bolt and collect seed.' },
  ],
  nutrition: {
    calories: 23, water: 91.4, protein: 2.9, carbs: 3.6, fiber: 2.2, sugars: 0.4, fat: 0.4,
    saturated: 0.1, monounsat: 0, polyunsat: 0.2,
    vitA: 469, vitD: 0, vitE: 2.0, vitK: 483,
    vitC: 28.1, vitB1: 0.08, vitB2: 0.19, vitB3: 0.7, vitB5: 0.07, vitB6: 0.2,
    vitB7: 0, vitB9: 194, vitB12: 0, choline: 19.3,
    calcium: 99, phosphorus: 49, magnesium: 79, sodium: 79, potassium: 558, chloride: 0,
    iron: 2.7, zinc: 0.53, copper: 0.13, manganese: 0.9, selenium: 1.0, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Extraordinary nutrient density. One of the highest folate foods (194 µg per 100g). Very high vitamin K, vitamin A, magnesium, and iron. Oxalic acid binds some iron and calcium — cooking reduces oxalate levels and increases mineral bioavailability.',
  },
  size: { weight: 'N/A — harvested by leaf', dimensions: 'Mature leaves 3–8" long', notes: 'Savoy spinach has crinkled leaves that trap grit — wash thoroughly; flat-leaf types (Tyee) are easier to clean' },
});
