import Crop from '../Crop.js';
export default new Crop({
  id: 'tomatoes',
  name: 'Tomatoes',
  cat: 'Fruiting Veg',
  emoji: '🍅',
  planting: {
    zone6: 'Start indoors late Mar–early Apr (6–8 weeks before last frost); transplant mid-May after last frost',
    depth: 'Plant deep — bury ⅔ of stem; roots grow from buried stem nodes',
    spacing: '18–24" (determinate/cage); 24–36" (indeterminate/staked)',
    ph: '6.0–6.8',
    sun: 'Full sun (8+ hours)',
    zone3: 'Start indoors early Apr; transplant Jun; short-season varieties (Early Girl, Stupice)',
    zone4: 'Start indoors early Apr; transplant late May',
    zone5: 'Start indoors late Mar; transplant mid-May',
    zone7: 'Start indoors Mar; transplant Apr',
    zone8: 'Start indoors Jan–Feb; transplant Mar; second crop starts Jun for fall harvest',
    zone9: 'Start indoors Jan; transplant Feb–Mar; fall crop from Jul planting',
  },
  zones: {
    '6': { timing: 'Transplant mid-May; harvest Jul–Oct (60–85 days from transplant)', plantingStart: 5, plantingEnd: 6, harvestStart: 7, harvestEnd: 10 },
  },
  special: 'Indeterminate varieties (Brandywine, Cherokee Purple, Sun Gold) grow all season and need tall stakes or cages. Determinate (Roma, Celebrity) stop at a set height — good for canning. Always bury deep — the buried stem develops roots for stronger plants. Sucker removal (indeterminate types) increases fruit size. Consistent watering prevents blossom end rot and cracking.',
  water: { in: '1.5–2', note: 'Consistent, deep watering is critical. Inconsistent moisture causes blossom end rot (calcium uptake failure) and fruit cracking. Water deeply 2–3 times per week rather than lightly every day. Mulch heavily to retain moisture.' },
  fertilizer: { type: 'Balanced at planting; high phosphorus at flowering; high potassium at fruiting', amount: 'Starter: 1 tbsp 5-10-10 in planting hole; ongoing: ¼ cup balanced fertilizer per plant', freq: 'Every 3–4 weeks through season; switch to low-nitrogen when first fruits set to prevent excessive foliage at expense of fruit' },
  companions: {
    good: [
      { name: 'Basil', why: 'Repels thrips, aphids, and hornworm; may improve tomato flavor — classic pairing' },
      { name: 'Marigolds', why: 'Deter whiteflies, nematodes, and aphids — most widely recommended tomato companion' },
      { name: 'Parsley', why: 'Attracts predatory wasps; provides habitat for beneficial insects' },
      { name: 'Garlic', why: 'Deters aphids, spider mites, and early blight organisms' },
      { name: 'Asparagus', why: 'Asparagus repels nematodes that attack tomato roots; tomatoes repel asparagus beetles' },
      { name: 'Carrots', why: 'Loose carrot roots aerate soil around tomato roots; no resource competition' },
      { name: 'Borage', why: 'Repels tomato hornworm and attracts bees; trace mineral accumulator' },
    ],
    bad: [
      { name: 'Fennel', why: 'Strongly allelopathic — inhibits tomato growth and attracts tomato pests' },
      { name: 'Cabbage', why: 'Allelopathic interaction; both suffer when planted together' },
      { name: 'Potatoes', why: 'Both susceptible to late blight (Phytophthora infestans) — keep strictly separated to limit disease spread' },
      { name: 'Corn', why: 'Both attract corn earworm / tomato fruitworm (same pest)' },
      { name: 'Dill (mature)', why: 'Mature dill inhibits tomato growth; young dill is beneficial' },
    ],
  },
  companionDist: 'Plant basil 12–18 inches from tomatoes; marigolds every 18 inches throughout the tomato bed; garlic at ends of rows',
  animals: 'Bees essential for pollination (vibration-pollinated — buzz pollination by bumble bees is most effective). Parasitic wasps control hornworm. Ladybugs prey on aphids.',
  diseases: [
    { name: 'Early Blight', desc: 'Dark concentric-ring lesions on lower leaves; spreads upward. Most common tomato disease. Remove affected leaves; apply copper or chlorothalonil fungicide; mulch to prevent soil splash; space for air circulation.' },
    { name: 'Late Blight', desc: 'Water-soaked grey-green lesions on leaves and fruit; white sporulation in humid conditions. Spreads explosively — destroys entire crop in days. Apply copper fungicide preventively in cool, wet weather; remove and destroy infected plants immediately; do not compost.' },
    { name: 'Septoria Leaf Spot', desc: 'Small circular spots with white centers and dark borders on lower leaves. Very common; manageable. Remove affected leaves; copper spray; mulch.' },
    { name: 'Fusarium / Verticillium Wilt', desc: 'Yellowing and wilting; brown vascular tissue when stem is cut. No cure. Plant resistant varieties (F, V, N, T designations on seed packet); long rotation (4+ years).' },
    { name: 'Blossom End Rot', desc: 'Black sunken area on blossom end of fruit. Calcium deficiency caused by inconsistent watering — not a disease. Maintain even moisture; calcium spray as temporary fix; mulch heavily.' },
  ],
  pests: 'Tomato hornworm (hand-pick; Bt spray; look for parasitized hornworms with white wasp cocoons and leave those), aphids (blast with water; neem; ladybug release), whiteflies (yellow sticky traps; insecticidal soap), stinkbugs (exclude with row cover; hand-pick), flea beetles (diatomaceous earth; row covers early season).',
  rotation: { family: 'Solanaceae (Nightshade family)', cycle: 'Rotate every 3–4 years; do not follow peppers, eggplant, or potatoes in same bed; avoid beds with known Fusarium or Verticillium history' },
  stages: [
    { label: 'Seedling', title: 'Indoor start', desc: 'Start under grow lights (14–16 hours). Pot up twice before transplant. Harden off 10–14 days. Tomatoes are ready when 6–8 inches tall and stocky, not leggy.' },
    { label: 'Transplant', title: 'Establishment', desc: 'Bury deep — up to ⅔ of stem. Water thoroughly. Protect from late frost with row cover. Growth slow for 1–2 weeks while roots establish.' },
    { label: 'Bloom', title: 'First flowers', desc: 'Yellow flowers appear 5–7 weeks after transplant. Shake plants or use electric toothbrush to improve pollination in still air. First blossom cluster often determines plant productivity.' },
    { label: 'Fruit set', title: 'Fruitlet development', desc: 'Tiny tomatoes appear. Maintain consistent watering — critical period for preventing blossom end rot.' },
    { label: 'Harvest', title: 'Ripe tomatoes', desc: 'Pick when fully colored and slightly soft. Tomatoes continue to ripen at room temperature (never refrigerate — cold destroys flavor). Pull plants before hard frost; green tomatoes ripen indoors.' },
  ],
  nutrition: {
    calories: 18, water: 94.5, protein: 0.9, carbs: 3.9, fiber: 1.2, sugars: 2.6, fat: 0.2,
    saturated: 0, monounsat: 0, polyunsat: 0.1,
    vitA: 42, vitD: 0, vitE: 0.5, vitK: 7.9,
    vitC: 13.7, vitB1: 0.04, vitB2: 0.02, vitB3: 0.6, vitB5: 0.09, vitB6: 0.08,
    vitB7: 4.0, vitB9: 15, vitB12: 0, choline: 6.7,
    calcium: 10, phosphorus: 24, magnesium: 11, sodium: 5, potassium: 237, chloride: 0,
    iron: 0.3, zinc: 0.17, copper: 0.06, manganese: 0.11, selenium: 0, iodine: 0,
    chromium: 0, molybdenum: 0, fluoride: 0,
    notes: 'Rich in lycopene — a carotenoid with strong cancer-protective properties, especially prostate cancer. Lycopene is more bioavailable from cooked tomatoes with fat (e.g. tomato sauce with olive oil) than from raw. Also contains chlorogenic acid and rutin.',
  },
  size: { weight: '80–300g (slicers); 20–50g (cherry)', dimensions: '2–4" diameter (slicers); ¾–1.5" (cherry/grape)', notes: 'Heirloom slicers (Brandywine, Cherokee Purple) have best flavor; cherry types (Sun Gold, Sweet 100) are most productive; paste types (Roma, San Marzano) have lowest water content for cooking' },
});
